"""EntroQ authz example client.

Demonstrates:
- Generating a self-signed JWT (stand-in for a real IDP token)
- Using the JWT as a Bearer token against an OPA-protected EntroQ service
- Showing which queue operations are allowed and denied based on policy

To run:
    pip install requests pyjwt cryptography
    python client.py

The private key in example-key.pem was generated by keygen.py and corresponds
to the inline JWKS in opa/data.json. OPA uses the public key to verify tokens.

In production:
- Replace make_token() with your IDP's token acquisition (OAuth2, OIDC, etc.)
- Replace opa/user.rego with the reference implementation that fetches JWKS
  from data.entroq.idp.jwks_url at evaluation time.
- Remove example-key.pem; the private key lives with your IDP.
"""

import json
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

import jwt
import requests

ENTROQ_URL = "http://localhost:9100"
KEY_FILE = Path(__file__).parent / "example-key.pem"
DATA_FILE = Path(__file__).parent / "opa" / "data.json"

AUDIENCE = "entroq-example"
ISSUER = "entroq-example-issuer"


def make_token(subject: str, expiry: timedelta = timedelta(hours=1)) -> str:
    """Sign a JWT for the given subject using the example private key.

    In production, replace this with token acquisition from your IDP.
    The token format (RS256 JWT with sub/aud/iss claims) is what the
    reference user.rego expects to verify.
    """
    private_key = KEY_FILE.read_text()
    now = datetime.now(timezone.utc)
    payload = {
        "sub": subject,
        "aud": AUDIENCE,
        "iss": ISSUER,
        "iat": now,
        "exp": now + expiry,
    }
    return jwt.encode(payload, private_key, algorithm="RS256")


def make_session(token: str) -> requests.Session:
    """Create an HTTP session that sends the Bearer token on every request."""
    session = requests.Session()
    session.headers["Authorization"] = f"Bearer {token}"
    return session


def try_request(session: requests.Session, method: str, url: str, **kwargs) -> tuple[bool, object]:
    """Make a request and return (ok, body_or_error)."""
    resp = session.request(method, url, **kwargs)
    if resp.ok:
        return True, resp.json() if resp.content else None
    return False, f"HTTP {resp.status_code}: {resp.text[:200]}"


def show(label: str, ok: bool, detail: object) -> None:
    status = "ALLOWED" if ok else "DENIED "
    print(f"  [{status}] {label}")
    if not ok:
        print(f"           {detail}")


def demo_user(name: str, subject: str) -> None:
    print(f"\n--- {name} ({subject}) ---")
    token = make_token(subject)
    session = make_session(token)
    base = ENTROQ_URL

    # Insert into personal namespace (auto-granted to everyone).
    ok, body = try_request(session, "POST", f"{base}/api/v0/modify", json={
        "claimantId": "demo-client",
        "inserts": [{"queue": f"/users/{subject}/inbox", "value": json.dumps("hello")}],
    })
    show(f"insert into /users/{subject}/inbox", ok, body)

    # Insert into /shared/ (writers role only).
    ok, body = try_request(session, "POST", f"{base}/api/v0/modify", json={
        "claimantId": "demo-client",
        "inserts": [{"queue": "/shared/work", "value": json.dumps("shared task")}],
    })
    show("insert into /shared/work", ok, body)

    # Read /shared/inbox (alice via writers role, bob directly).
    ok, body = try_request(session, "GET", f"{base}/api/v0/tasks",
                           params={"queue": "/shared/inbox"})
    show("read /shared/inbox", ok, body)

    # Insert into another user's personal namespace (always denied).
    other = "bob" if subject == "alice" else "alice"
    ok, body = try_request(session, "POST", f"{base}/api/v0/modify", json={
        "claimantId": "demo-client",
        "inserts": [{"queue": f"/users/{other}/inbox", "value": json.dumps("intruder")}],
    })
    show(f"insert into /users/{other}/inbox (should be denied)", ok, body)


def main() -> None:
    print(f"EntroQ authz example -- service at {ENTROQ_URL}")
    print("Policy summary:")
    data = json.loads(DATA_FILE.read_text())
    policy = data["entroq"]["policy"]
    for u in policy["users"]:
        print(f"  user {u['name']!r}: queues={u['queues']}, roles={u['roles']}")
    for r in policy["roles"]:
        print(f"  role {r['name']!r}: queues={r['queues']}")

    # Check service is up.
    try:
        requests.get(f"{ENTROQ_URL}/api/v0/time", timeout=3).raise_for_status()
    except Exception as e:
        print(f"\nCannot reach EntroQ at {ENTROQ_URL}: {e}", file=sys.stderr)
        print("Is the docker-compose stack running?", file=sys.stderr)
        sys.exit(1)

    demo_user("Alice", "alice")
    demo_user("Bob", "bob")

    print()


if __name__ == "__main__":
    main()
