// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: entroq.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/shiblon/entroq/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EntroQName is the fully-qualified name of the EntroQ service.
	EntroQName = "api.EntroQ"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EntroQTryClaimProcedure is the fully-qualified name of the EntroQ's TryClaim RPC.
	EntroQTryClaimProcedure = "/api.EntroQ/TryClaim"
	// EntroQClaimProcedure is the fully-qualified name of the EntroQ's Claim RPC.
	EntroQClaimProcedure = "/api.EntroQ/Claim"
	// EntroQModifyProcedure is the fully-qualified name of the EntroQ's Modify RPC.
	EntroQModifyProcedure = "/api.EntroQ/Modify"
	// EntroQTasksProcedure is the fully-qualified name of the EntroQ's Tasks RPC.
	EntroQTasksProcedure = "/api.EntroQ/Tasks"
	// EntroQQueuesProcedure is the fully-qualified name of the EntroQ's Queues RPC.
	EntroQQueuesProcedure = "/api.EntroQ/Queues"
	// EntroQQueueStatsProcedure is the fully-qualified name of the EntroQ's QueueStats RPC.
	EntroQQueueStatsProcedure = "/api.EntroQ/QueueStats"
	// EntroQTimeProcedure is the fully-qualified name of the EntroQ's Time RPC.
	EntroQTimeProcedure = "/api.EntroQ/Time"
	// EntroQStreamTasksProcedure is the fully-qualified name of the EntroQ's StreamTasks RPC.
	EntroQStreamTasksProcedure = "/api.EntroQ/StreamTasks"
)

// EntroQClient is a client for the api.EntroQ service.
type EntroQClient interface {
	TryClaim(context.Context, *connect.Request[api.ClaimRequest]) (*connect.Response[api.ClaimResponse], error)
	Claim(context.Context, *connect.Request[api.ClaimRequest]) (*connect.Response[api.ClaimResponse], error)
	Modify(context.Context, *connect.Request[api.ModifyRequest]) (*connect.Response[api.ModifyResponse], error)
	Tasks(context.Context, *connect.Request[api.TasksRequest]) (*connect.Response[api.TasksResponse], error)
	Queues(context.Context, *connect.Request[api.QueuesRequest]) (*connect.Response[api.QueuesResponse], error)
	QueueStats(context.Context, *connect.Request[api.QueuesRequest]) (*connect.Response[api.QueuesResponse], error)
	Time(context.Context, *connect.Request[api.TimeRequest]) (*connect.Response[api.TimeResponse], error)
	// This is set to stream TasksResponse instead of just sending all tasks in a
	// single one. Typically this will have one task per response, but it is best
	// for the client to consume however many there are.
	StreamTasks(context.Context, *connect.Request[api.TasksRequest]) (*connect.ServerStreamForClient[api.TasksResponse], error)
}

// NewEntroQClient constructs a client for the api.EntroQ service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEntroQClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EntroQClient {
	baseURL = strings.TrimRight(baseURL, "/")
	entroQMethods := api.File_entroq_proto.Services().ByName("EntroQ").Methods()
	return &entroQClient{
		tryClaim: connect.NewClient[api.ClaimRequest, api.ClaimResponse](
			httpClient,
			baseURL+EntroQTryClaimProcedure,
			connect.WithSchema(entroQMethods.ByName("TryClaim")),
			connect.WithClientOptions(opts...),
		),
		claim: connect.NewClient[api.ClaimRequest, api.ClaimResponse](
			httpClient,
			baseURL+EntroQClaimProcedure,
			connect.WithSchema(entroQMethods.ByName("Claim")),
			connect.WithClientOptions(opts...),
		),
		modify: connect.NewClient[api.ModifyRequest, api.ModifyResponse](
			httpClient,
			baseURL+EntroQModifyProcedure,
			connect.WithSchema(entroQMethods.ByName("Modify")),
			connect.WithClientOptions(opts...),
		),
		tasks: connect.NewClient[api.TasksRequest, api.TasksResponse](
			httpClient,
			baseURL+EntroQTasksProcedure,
			connect.WithSchema(entroQMethods.ByName("Tasks")),
			connect.WithClientOptions(opts...),
		),
		queues: connect.NewClient[api.QueuesRequest, api.QueuesResponse](
			httpClient,
			baseURL+EntroQQueuesProcedure,
			connect.WithSchema(entroQMethods.ByName("Queues")),
			connect.WithClientOptions(opts...),
		),
		queueStats: connect.NewClient[api.QueuesRequest, api.QueuesResponse](
			httpClient,
			baseURL+EntroQQueueStatsProcedure,
			connect.WithSchema(entroQMethods.ByName("QueueStats")),
			connect.WithClientOptions(opts...),
		),
		time: connect.NewClient[api.TimeRequest, api.TimeResponse](
			httpClient,
			baseURL+EntroQTimeProcedure,
			connect.WithSchema(entroQMethods.ByName("Time")),
			connect.WithClientOptions(opts...),
		),
		streamTasks: connect.NewClient[api.TasksRequest, api.TasksResponse](
			httpClient,
			baseURL+EntroQStreamTasksProcedure,
			connect.WithSchema(entroQMethods.ByName("StreamTasks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// entroQClient implements EntroQClient.
type entroQClient struct {
	tryClaim    *connect.Client[api.ClaimRequest, api.ClaimResponse]
	claim       *connect.Client[api.ClaimRequest, api.ClaimResponse]
	modify      *connect.Client[api.ModifyRequest, api.ModifyResponse]
	tasks       *connect.Client[api.TasksRequest, api.TasksResponse]
	queues      *connect.Client[api.QueuesRequest, api.QueuesResponse]
	queueStats  *connect.Client[api.QueuesRequest, api.QueuesResponse]
	time        *connect.Client[api.TimeRequest, api.TimeResponse]
	streamTasks *connect.Client[api.TasksRequest, api.TasksResponse]
}

// TryClaim calls api.EntroQ.TryClaim.
func (c *entroQClient) TryClaim(ctx context.Context, req *connect.Request[api.ClaimRequest]) (*connect.Response[api.ClaimResponse], error) {
	return c.tryClaim.CallUnary(ctx, req)
}

// Claim calls api.EntroQ.Claim.
func (c *entroQClient) Claim(ctx context.Context, req *connect.Request[api.ClaimRequest]) (*connect.Response[api.ClaimResponse], error) {
	return c.claim.CallUnary(ctx, req)
}

// Modify calls api.EntroQ.Modify.
func (c *entroQClient) Modify(ctx context.Context, req *connect.Request[api.ModifyRequest]) (*connect.Response[api.ModifyResponse], error) {
	return c.modify.CallUnary(ctx, req)
}

// Tasks calls api.EntroQ.Tasks.
func (c *entroQClient) Tasks(ctx context.Context, req *connect.Request[api.TasksRequest]) (*connect.Response[api.TasksResponse], error) {
	return c.tasks.CallUnary(ctx, req)
}

// Queues calls api.EntroQ.Queues.
func (c *entroQClient) Queues(ctx context.Context, req *connect.Request[api.QueuesRequest]) (*connect.Response[api.QueuesResponse], error) {
	return c.queues.CallUnary(ctx, req)
}

// QueueStats calls api.EntroQ.QueueStats.
func (c *entroQClient) QueueStats(ctx context.Context, req *connect.Request[api.QueuesRequest]) (*connect.Response[api.QueuesResponse], error) {
	return c.queueStats.CallUnary(ctx, req)
}

// Time calls api.EntroQ.Time.
func (c *entroQClient) Time(ctx context.Context, req *connect.Request[api.TimeRequest]) (*connect.Response[api.TimeResponse], error) {
	return c.time.CallUnary(ctx, req)
}

// StreamTasks calls api.EntroQ.StreamTasks.
func (c *entroQClient) StreamTasks(ctx context.Context, req *connect.Request[api.TasksRequest]) (*connect.ServerStreamForClient[api.TasksResponse], error) {
	return c.streamTasks.CallServerStream(ctx, req)
}

// EntroQHandler is an implementation of the api.EntroQ service.
type EntroQHandler interface {
	TryClaim(context.Context, *connect.Request[api.ClaimRequest]) (*connect.Response[api.ClaimResponse], error)
	Claim(context.Context, *connect.Request[api.ClaimRequest]) (*connect.Response[api.ClaimResponse], error)
	Modify(context.Context, *connect.Request[api.ModifyRequest]) (*connect.Response[api.ModifyResponse], error)
	Tasks(context.Context, *connect.Request[api.TasksRequest]) (*connect.Response[api.TasksResponse], error)
	Queues(context.Context, *connect.Request[api.QueuesRequest]) (*connect.Response[api.QueuesResponse], error)
	QueueStats(context.Context, *connect.Request[api.QueuesRequest]) (*connect.Response[api.QueuesResponse], error)
	Time(context.Context, *connect.Request[api.TimeRequest]) (*connect.Response[api.TimeResponse], error)
	// This is set to stream TasksResponse instead of just sending all tasks in a
	// single one. Typically this will have one task per response, but it is best
	// for the client to consume however many there are.
	StreamTasks(context.Context, *connect.Request[api.TasksRequest], *connect.ServerStream[api.TasksResponse]) error
}

// NewEntroQHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEntroQHandler(svc EntroQHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	entroQMethods := api.File_entroq_proto.Services().ByName("EntroQ").Methods()
	entroQTryClaimHandler := connect.NewUnaryHandler(
		EntroQTryClaimProcedure,
		svc.TryClaim,
		connect.WithSchema(entroQMethods.ByName("TryClaim")),
		connect.WithHandlerOptions(opts...),
	)
	entroQClaimHandler := connect.NewUnaryHandler(
		EntroQClaimProcedure,
		svc.Claim,
		connect.WithSchema(entroQMethods.ByName("Claim")),
		connect.WithHandlerOptions(opts...),
	)
	entroQModifyHandler := connect.NewUnaryHandler(
		EntroQModifyProcedure,
		svc.Modify,
		connect.WithSchema(entroQMethods.ByName("Modify")),
		connect.WithHandlerOptions(opts...),
	)
	entroQTasksHandler := connect.NewUnaryHandler(
		EntroQTasksProcedure,
		svc.Tasks,
		connect.WithSchema(entroQMethods.ByName("Tasks")),
		connect.WithHandlerOptions(opts...),
	)
	entroQQueuesHandler := connect.NewUnaryHandler(
		EntroQQueuesProcedure,
		svc.Queues,
		connect.WithSchema(entroQMethods.ByName("Queues")),
		connect.WithHandlerOptions(opts...),
	)
	entroQQueueStatsHandler := connect.NewUnaryHandler(
		EntroQQueueStatsProcedure,
		svc.QueueStats,
		connect.WithSchema(entroQMethods.ByName("QueueStats")),
		connect.WithHandlerOptions(opts...),
	)
	entroQTimeHandler := connect.NewUnaryHandler(
		EntroQTimeProcedure,
		svc.Time,
		connect.WithSchema(entroQMethods.ByName("Time")),
		connect.WithHandlerOptions(opts...),
	)
	entroQStreamTasksHandler := connect.NewServerStreamHandler(
		EntroQStreamTasksProcedure,
		svc.StreamTasks,
		connect.WithSchema(entroQMethods.ByName("StreamTasks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.EntroQ/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EntroQTryClaimProcedure:
			entroQTryClaimHandler.ServeHTTP(w, r)
		case EntroQClaimProcedure:
			entroQClaimHandler.ServeHTTP(w, r)
		case EntroQModifyProcedure:
			entroQModifyHandler.ServeHTTP(w, r)
		case EntroQTasksProcedure:
			entroQTasksHandler.ServeHTTP(w, r)
		case EntroQQueuesProcedure:
			entroQQueuesHandler.ServeHTTP(w, r)
		case EntroQQueueStatsProcedure:
			entroQQueueStatsHandler.ServeHTTP(w, r)
		case EntroQTimeProcedure:
			entroQTimeHandler.ServeHTTP(w, r)
		case EntroQStreamTasksProcedure:
			entroQStreamTasksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEntroQHandler returns CodeUnimplemented from all methods.
type UnimplementedEntroQHandler struct{}

func (UnimplementedEntroQHandler) TryClaim(context.Context, *connect.Request[api.ClaimRequest]) (*connect.Response[api.ClaimResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.EntroQ.TryClaim is not implemented"))
}

func (UnimplementedEntroQHandler) Claim(context.Context, *connect.Request[api.ClaimRequest]) (*connect.Response[api.ClaimResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.EntroQ.Claim is not implemented"))
}

func (UnimplementedEntroQHandler) Modify(context.Context, *connect.Request[api.ModifyRequest]) (*connect.Response[api.ModifyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.EntroQ.Modify is not implemented"))
}

func (UnimplementedEntroQHandler) Tasks(context.Context, *connect.Request[api.TasksRequest]) (*connect.Response[api.TasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.EntroQ.Tasks is not implemented"))
}

func (UnimplementedEntroQHandler) Queues(context.Context, *connect.Request[api.QueuesRequest]) (*connect.Response[api.QueuesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.EntroQ.Queues is not implemented"))
}

func (UnimplementedEntroQHandler) QueueStats(context.Context, *connect.Request[api.QueuesRequest]) (*connect.Response[api.QueuesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.EntroQ.QueueStats is not implemented"))
}

func (UnimplementedEntroQHandler) Time(context.Context, *connect.Request[api.TimeRequest]) (*connect.Response[api.TimeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.EntroQ.Time is not implemented"))
}

func (UnimplementedEntroQHandler) StreamTasks(context.Context, *connect.Request[api.TasksRequest], *connect.ServerStream[api.TasksResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.EntroQ.StreamTasks is not implemented"))
}
