apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: entroq
  labels:
    app: entroq
spec:
  selector:
    matchLabels:
      app: entroq
  serviceName: entroq
  replicas: 1
  template:
    metadata:
      labels:
        app: entroq
    spec:
      containers:
        - name: entroq
          image: shiblon/entroq:v0.4
          ports:
            - containerPort: 37706
              name: grpc
            - containerPort: 9100
              name: metrics
        - name: eqc
          image: shiblon/entroq:v0.4
          command:
            - tail
            - -f
            - /dev/null
      volumes:
        - name: proxy-config
          configMap:
            name: entroq-envoy-config
