version: "3.3"

services:
  entroq:
    image: shiblon/entroq:v0.5
    command: ["--authz", "opahttp", "--opa_url", "http://opa:8181"]

  opa:
    image: openpolicyagent/opa:0.26.0
    command:
      - "run"
      - "--addr=:8181"
      - "--server"
      - "--watch"
      - "--set-file=data=/etc/opa/config/example-data/data.json"
      - "/etc/opa/config/core"
      - "/etc/opa/config/example"
    volumes:
      - "./opadata:/etc/opa/config"
