{{- if and (eq .Values.backend "pg") (not .Values.postgresql.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "entroq.fullname" . }}
  labels:
    {{- include "entroq.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.password | quote }}
{{- end }}
