apiVersion: v1
kind: Service
metadata:
  name: {{ include "entroq.fullname" . }}
  labels:
    {{- include "entroq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "entroq.selectorLabels" . | nindent 4 }}
Line 19: 
