# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import entroq_pb2 as entroq__pb2


class EntroQStub(object):
  """EntroQ is a service that allows for access to a task queue.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TryClaim = channel.unary_unary(
        '/proto.EntroQ/TryClaim',
        request_serializer=entroq__pb2.ClaimRequest.SerializeToString,
        response_deserializer=entroq__pb2.ClaimResponse.FromString,
        )
    self.Claim = channel.unary_unary(
        '/proto.EntroQ/Claim',
        request_serializer=entroq__pb2.ClaimRequest.SerializeToString,
        response_deserializer=entroq__pb2.ClaimResponse.FromString,
        )
    self.Modify = channel.unary_unary(
        '/proto.EntroQ/Modify',
        request_serializer=entroq__pb2.ModifyRequest.SerializeToString,
        response_deserializer=entroq__pb2.ModifyResponse.FromString,
        )
    self.Tasks = channel.unary_unary(
        '/proto.EntroQ/Tasks',
        request_serializer=entroq__pb2.TasksRequest.SerializeToString,
        response_deserializer=entroq__pb2.TasksResponse.FromString,
        )
    self.Queues = channel.unary_unary(
        '/proto.EntroQ/Queues',
        request_serializer=entroq__pb2.QueuesRequest.SerializeToString,
        response_deserializer=entroq__pb2.QueuesResponse.FromString,
        )


class EntroQServicer(object):
  """EntroQ is a service that allows for access to a task queue.
  """

  def TryClaim(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Claim(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Modify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Tasks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Queues(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EntroQServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TryClaim': grpc.unary_unary_rpc_method_handler(
          servicer.TryClaim,
          request_deserializer=entroq__pb2.ClaimRequest.FromString,
          response_serializer=entroq__pb2.ClaimResponse.SerializeToString,
      ),
      'Claim': grpc.unary_unary_rpc_method_handler(
          servicer.Claim,
          request_deserializer=entroq__pb2.ClaimRequest.FromString,
          response_serializer=entroq__pb2.ClaimResponse.SerializeToString,
      ),
      'Modify': grpc.unary_unary_rpc_method_handler(
          servicer.Modify,
          request_deserializer=entroq__pb2.ModifyRequest.FromString,
          response_serializer=entroq__pb2.ModifyResponse.SerializeToString,
      ),
      'Tasks': grpc.unary_unary_rpc_method_handler(
          servicer.Tasks,
          request_deserializer=entroq__pb2.TasksRequest.FromString,
          response_serializer=entroq__pb2.TasksResponse.SerializeToString,
      ),
      'Queues': grpc.unary_unary_rpc_method_handler(
          servicer.Queues,
          request_deserializer=entroq__pb2.QueuesRequest.FromString,
          response_serializer=entroq__pb2.QueuesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.EntroQ', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
