#!/usr/bin/env bash

img_name=${IMAGE_NAME%%:*}
img_tag=${IMAGE_NAME#*:}

to_push=("$IMAGE_NAME")

if [[ "$img_tag" =~ ^pg-.*$ ]]; then
  docker build -t $IMAGE_NAME -f pg/Dockerfile .
else
  docker build -t $IMAGE_NAME -f Dockerfile .
fi

if [[ "img_tag" =~ ^(pg-)?v?([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
  major_minor_img="${img_name}:${img_tag%.*}"
  major_img="${img_name}:${major_minor%.*}"

  to_push+=("$major_img" "$minor_img")

  docker tag "$IMAGE_NAME" "$major_minor_img"
  docker tag "$IMAGE_NAME" "$major_img"
fi

for img in "${to_push[@]}"; do
  docker push "$img"
done
