package async

import (
	"context"
	"fmt"

	"github.com/shiblon/entroq"
	"github.com/shiblon/entroq/pkg/worker"
	"golang.org/x/sync/errgroup"
)

// Forwarder bridges tasks from one EntroQ instance to another. It claims
// tasks from a source queue, inserts them into a destination queue on a
// separate EntroQ instance, then deletes from the source.
//
// # Delivery semantics
//
// Delivery is at-least-once. The insert into the destination and the delete
// from the source are separate transactions. A crash between them causes the
// source task to expire and be re-forwarded, producing a duplicate task on
// the destination. Workers consuming from the destination queue must therefore
// be idempotent: given the same payload they must produce the same outcome.
//
// Any unique tokens a downstream consumer needs (idempotency keys, nonces,
// correlation IDs) should be embedded in the task value by the original
// producer, not generated by the consumer on each processing attempt.
type Forwarder struct {
	src         *entroq.EntroQ
	dst         *entroq.EntroQ
	srcQueue    string
	dstQueue    string
	concurrency int
}

// ForwarderOption configures a Forwarder.
type ForwarderOption func(*Forwarder)

// WithForwarderConcurrency sets the number of concurrent forwarding workers.
// Defaults to 1.
func WithForwarderConcurrency(n int) ForwarderOption {
	return func(f *Forwarder) {
		f.concurrency = n
	}
}

// WithForwarderDestQueue sets the destination queue name. Defaults to the
// source queue name.
func WithForwarderDestQueue(q string) ForwarderOption {
	return func(f *Forwarder) {
		f.dstQueue = q
	}
}

// NewForwarder creates a Forwarder that claims tasks from srcQueue on src and
// re-inserts them into the destination queue on dst.
func NewForwarder(src, dst *entroq.EntroQ, srcQueue string, opts ...ForwarderOption) *Forwarder {
	f := &Forwarder{
		src:         src,
		dst:         dst,
		srcQueue:    srcQueue,
		dstQueue:    srcQueue,
		concurrency: 1,
	}
	for _, o := range opts {
		o(f)
	}
	return f
}

// Run starts the forwarding workers and blocks until ctx is canceled or an
// unrecoverable error occurs.
func (f *Forwarder) Run(ctx context.Context) error {
	dstQueue := f.dstQueue
	dst := f.dst

	fwdWorker := worker.New(f.src,
		worker.WithDoWork(func(ctx context.Context, task *entroq.Task, val []byte, _ []*entroq.Doc) error {
			_, err := dst.Modify(ctx, entroq.InsertingInto(dstQueue, entroq.WithRawValue(val)))
			return err
		}),
		worker.WithFinish(func(ctx context.Context, task *entroq.Task, _ []byte, _ []*entroq.Doc) error {
			_, err := f.src.Modify(ctx, task.Delete())
			return err
		}),
	)

	g, ctx := errgroup.WithContext(ctx)
	for range f.concurrency {
		g.Go(func() error {
			if err := fwdWorker.Run(ctx, worker.Watching(f.srcQueue)); err != nil {
				return fmt.Errorf("forwarder worker: %w", err)
			}
			return nil
		})
	}
	return g.Wait()
}
