package async

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"log/slog"
	"net"
	"net/http"
	"path"
	"strings"
	"sync"
	"time"

	"github.com/shiblon/entroq"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/noop"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"google.golang.org/grpc/metadata"
)

// Sender is an http.Handler that accepts outgoing HTTP calls from a local
// service and routes them through EntroQ task queues. Each request is
// translated into a task on the target queue, and the sender relays response
// frames from an ephemeral per-request queue until a terminal frame arrives.
//
// Queue routing: the target queue is derived from the request's Host header,
// not its path. The configured domain suffix (see WithSenderDomainSuffix) is
// stripped from the host, the remaining dotted labels become queue path
// segments, and a single-label host is prefixed with the default namespace
// (see WithSenderNamespace). With the default ".localhost" suffix,
// "payments.localhost" targets "/payments" and "orders.acme.localhost" targets
// "/orders/acme"; the task is enqueued on that target's "/inbox" subqueue. The
// request's full path and query string are forwarded unchanged in the
// envelope, so the upstream's own router dispatches by path exactly as it would
// for a direct call.
//
// # Failure semantics
//
// Before a session is established, the initial task retains ordinary EntroQ
// claim/retry behavior. Once the receiver has atomically moved it to a private
// lane and opened the upstream HTTP request, the live socket exists only in
// that receiver process. A receiver crash therefore terminates the exchange;
// it does not replay an in-progress HTTP stream on another replica. The caller
// must reconnect or retry, just as it would after a direct HTTP connection
// failure. EQLink does not replay the streaming request body, so callers must
// provide any retry policy and idempotency key required by their protocol.
//
// Any unique tokens the caller needs (idempotency keys, nonces, correlation
// IDs) should be generated by the caller and embedded in the request payload
// before the task is enqueued. Generating them inside the handler produces a
// different value on each replay, which defeats idempotency.
//
// If the sender disconnects, the upstream may continue until its current lane
// expires. Ephemeral tasks and the receiver-owned connection document are then
// garbage-collected. Upstream work cannot be undone; callers that care about
// exactly-once effects must track completion state themselves.
type Sender struct {
	sync.Mutex

	eq           *entroq.EntroQ
	domainSuffix string
	namespace    string
	name         string
	auditLog     *slog.Logger
	heartbeat    heartbeatTiming
	laneTiming   laneTiming
	addr         string
	mp           metric.MeterProvider
	tlsConfig    *tls.Config

	srv         *http.Server // set by Serve; Close uses it for shutdown
	metricsOnce sync.Once

	// OTel instruments, initialized on first use.
	metricInflight metric.Int64UpDownCounter
	metricHandled  metric.Int64Counter
	metricDuration metric.Float64Histogram
}

// SenderOption configures a Sender.
type SenderOption func(*Sender)

// WithSenderRequestTimeout sets the maximum silence from the peer before
// ServeHTTP gives up. An empty heartbeat is sent at one-third of this duration.
// Defaults to three minutes.
func WithSenderRequestTimeout(d time.Duration) SenderOption {
	return func(s *Sender) {
		s.heartbeat = heartbeatTimingForTimeout(d)
	}
}

// WithSenderMeterProvider sets the OTel MeterProvider used to create instruments.
// Defaults to metric.NewNoopMeterProvider() if not set.
func WithSenderMeterProvider(mp metric.MeterProvider) SenderOption {
	return func(s *Sender) {
		s.mp = mp
	}
}

// WithSenderTLSConfig sets the TLS configuration for the sender's HTTP server.
// If provided, the server will use this config for mTLS and identity extraction.
func WithSenderTLSConfig(cfg *tls.Config) SenderOption {
	return func(s *Sender) {
		s.tlsConfig = cfg
	}
}

// WithSenderDomainSuffix sets the domain suffix stripped from the Host header
// to derive the target service name. Defaults to ".localhost".
func WithSenderDomainSuffix(suffix string) SenderOption {
	return func(s *Sender) {
		s.domainSuffix = suffix
	}
}

// WithSenderNamespace sets the default namespace prepended to single-label
// host names. When the host resolves to a single service name (e.g. "bar"
// from "bar.localhost"), the namespace is prepended to form "ns/bar".
// Has no effect when the host already encodes a namespace (e.g. "ns.bar.localhost").
func WithSenderNamespace(ns string) SenderOption {
	return func(s *Sender) {
		s.namespace = ns
	}
}

// WithSenderName sets the service identity used in audit log entries as the
// "from" field. Typically the service's own queue prefix (e.g. "payments/svc-a").
// Has no effect when audit logging is disabled.
func WithSenderName(name string) SenderOption {
	return func(s *Sender) {
		s.name = name
	}
}

// WithSenderAuditLogger enables structured audit logging for every request
// the sender mediates. When set, three events are emitted per request:
// request_enqueued (on task insert) and response_received (on terminal frame).
// Payload content is never logged; only queue names, method, path, status,
// and timing are recorded.
func WithSenderAuditLogger(l *slog.Logger) SenderOption {
	return func(s *Sender) {
		s.auditLog = l
	}
}

// NewSender creates a Sender that listens on addr and routes outbound requests
// by extracting the target service from the Host header of incoming requests.
func NewSender(eq *entroq.EntroQ, addr string, opts ...SenderOption) *Sender {
	s := &Sender{
		eq:           eq,
		addr:         addr,
		domainSuffix: ".localhost",
		heartbeat:    defaultHeartbeatTiming,
		laneTiming:   defaultLaneTiming,
		mp:           noop.NewMeterProvider(),
	}
	for _, o := range opts {
		o(s)
	}
	// Initialize metrics eagerly so ServeHTTP is safe to call without Serve.
	// WithSenderMeterProvider must be applied before NewSender returns, so this
	// captures the final provider.
	if err := s.initMetrics(); err != nil {
		log.Printf("sender init metrics: %v", err)
	}
	return s
}

// initMetrics creates OTel instruments from the configured MeterProvider.
// Safe to call multiple times; only runs once.
func (s *Sender) initMetrics() error {
	var initErr error
	s.metricsOnce.Do(func() {
		initErr = s.doInitMetrics()
	})
	return initErr
}

func (s *Sender) doInitMetrics() error {
	m := s.mp.Meter("entroq/async/sender")
	var err error
	if s.metricInflight, err = m.Int64UpDownCounter("sender.inflight",
		metric.WithDescription("Number of in-flight requests currently being processed."),
	); err != nil {
		return fmt.Errorf("sender inflight counter: %w", err)
	}
	if s.metricHandled, err = m.Int64Counter("sender.handled_total",
		metric.WithDescription("Total number of requests handled by the sender."),
	); err != nil {
		return fmt.Errorf("sender handled counter: %w", err)
	}
	if s.metricDuration, err = m.Float64Histogram("sender.duration_seconds",
		metric.WithDescription("Request round-trip duration in seconds."),
		metric.WithUnit("s"),
	); err != nil {
		return fmt.Errorf("sender duration histogram: %w", err)
	}
	return nil
}

// Close gracefully shuts down the sender. It waits for all in-flight requests
// to complete (or ctx to expire), then shuts down the HTTP server.
//
// After Close returns, Run or Serve will also return.
func (s *Sender) Close(ctx context.Context) error {
	s.Lock()
	srv := s.srv
	s.Unlock()

	// Sequence: stop accepting new connections, then drain existing responses
	// from the queue (finish them out if possible).
	if err := srv.Shutdown(ctx); err != nil {
		return fmt.Errorf("sender shutdown: %w", err)
	}
	return nil
}

// Run starts the HTTP server on the address provided to NewSender and blocks
// until Close is called.
func (s *Sender) Run(ctx context.Context) error {
	lis, err := net.Listen("tcp", s.addr)
	if err != nil {
		return fmt.Errorf("sender listen: %w", err)
	}
	return s.Serve(ctx, lis)
}

// Serve starts the HTTP server on an already-open listener and blocks until
// Close is called. Useful when the caller needs to know the bound address
// before starting (e.g. when using ":0" for a random port in tests).
func (s *Sender) Serve(ctx context.Context, lis net.Listener) error {
	if err := s.initMetrics(); err != nil {
		return err
	}

	http2Server := &http2.Server{}
	handler := http.Handler(s)
	var tlsConfig *tls.Config
	if s.tlsConfig == nil {
		handler = h2c.NewHandler(handler, http2Server)
	} else {
		tlsConfig = s.tlsConfig.Clone()
	}

	s.Lock()
	s.srv = &http.Server{Handler: handler, TLSConfig: tlsConfig}
	srv := s.srv
	s.Unlock()

	var err error
	if tlsConfig != nil {
		if err := http2.ConfigureServer(srv, http2Server); err != nil {
			return fmt.Errorf("sender configure HTTP/2: %w", err)
		}
		err = srv.ServeTLS(lis, "", "")
	} else {
		err = srv.Serve(lis)
	}

	if err != nil && !errors.Is(err, http.ErrServerClosed) {
		return fmt.Errorf("sender serve: %w", err)
	}
	return nil
}

// ServeHTTP handles an outgoing request from the local service. It translates
// it into an Envelope task, enqueues it, then blocks until a Response task
// arrives on the ephemeral per-request response lane.
func (s *Sender) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	if err := s.laneTiming.validate(); err != nil {
		http.Error(w, fmt.Sprintf("invalid eqlink lane timing: %v", err), http.StatusInternalServerError)
		return
	}
	if err := s.heartbeat.validate(); err != nil {
		http.Error(w, fmt.Sprintf("invalid eqlink heartbeat timing: %v", err), http.StatusInternalServerError)
		return
	}

	s.metricInflight.Add(r.Context(), 1)
	defer func() {
		s.metricInflight.Add(r.Context(), -1)
		s.metricHandled.Add(r.Context(), 1)
		s.metricDuration.Record(r.Context(), time.Since(start).Seconds())
	}()

	ctx := r.Context()
	if err := http.NewResponseController(w).EnableFullDuplex(); err != nil && !errors.Is(err, http.ErrNotSupported) && r.ProtoMajor < 2 && r.ContentLength != 0 {
		http.Error(w, fmt.Sprintf("eqlink cannot enable full-duplex request streaming: %v", err), http.StatusNotImplemented)
		return
	}

	// If we have TLS peer certificates, use the Common Name as the identity
	// for the underlying EntroQ calls. This allows the backend to perform
	// authorization based on the mTLS identity of the caller.
	if r.TLS != nil && len(r.TLS.PeerCertificates) > 0 {
		cn := r.TLS.PeerCertificates[0].Subject.CommonName
		ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "mTLS "+cn)
	}

	// Protocol upgrades replace HTTP body semantics with another wire protocol
	// and remain outside EQLink's HTTP frame transport.
	if r.Header.Get("Upgrade") != "" {
		http.Error(w, "eqlink does not support protocol upgrades such as WebSocket; use HTTP/2 prior knowledge or TLS negotiation for streaming", http.StatusNotImplemented)
		return
	}

	queuePrefix, err := queueFromHost(r.Host, s.domainSuffix, s.namespace)
	if err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}
	targetInbox := path.Join(queuePrefix, "inbox")
	// RequestURI includes the query string; Path alone would drop it.
	forwardPath := r.URL.RequestURI()

	headers := copyHeaders(r.Header)

	session := entroq.GenHex16()
	requestAckLane := newReceiveLane(queuePrefix, session, "request-ack", time.Now(), s.laneTiming)
	responseDataLane := newReceiveLane(queuePrefix, session, "response-data", time.Now(), s.laneTiming)

	env := Envelope{
		FrameControl: FrameControl{
			Session:    session,
			ReplyQueue: requestAckLane.queue,
		},
		ResponseQueue: responseDataLane.queue,
		Method:        r.Method,
		Path:          forwardPath,
		ProtocolMajor: r.ProtoMajor,
		ContentLength: r.ContentLength,
		Headers:       headers,
		TrailerKeys:   trailerKeys(r.Trailer),
	}
	envValue, err := json.Marshal(env)
	if err != nil {
		http.Error(w, fmt.Sprintf("marshal envelope: %v", err), http.StatusInternalServerError)
		return
	}

	if _, err := s.eq.Modify(ctx,
		entroq.InsertingInto(targetInbox, entroq.WithRawValue(envValue)),
	); err != nil {
		log.Printf("sender enqueue to %s: %v", targetInbox, err)
		http.Error(w, fmt.Sprintf("enqueue task: %v", err), http.StatusBadGateway)
		return
	}
	if s.auditLog != nil {
		s.auditLog.LogAttrs(ctx, slog.LevelInfo, "request_enqueued",
			slog.String("from", s.name),
			slog.String("to", targetInbox),
			slog.String("method", r.Method),
			slog.String("path", r.URL.Path),
			slog.String("response_queue", responseDataLane.queue),
		)
	}

	sessionState := newSenderSession(s, w, r, session, requestAckLane, responseDataLane, start)
	if err := sessionState.run(ctx); err != nil {
		log.Printf("sender session %q: %v", session, err)
		if ctx.Err() != nil {
			return
		}
		if !sessionState.responseStarted {
			status := http.StatusBadGateway
			if errors.Is(err, errSenderPeerTimeout) || errors.Is(err, errSenderQueueExpired) {
				status = http.StatusGatewayTimeout
			}
			http.Error(w, err.Error(), status)
			return
		}
		// The status and some bytes may already be on the wire. Abort instead
		// of turning a truncated upstream stream into an apparently clean EOF.
		panic(http.ErrAbortHandler)
	}
}

// queueFromHost derives a queue prefix from an HTTP Host header value.
// It strips the port, then the configured domain suffix, and maps the remaining
// dot-separated labels left-to-right to a slash-separated queue path.
// The result always starts with "/" to match EntroQ queue naming conventions.
//
// If only one label remains after suffix stripping and namespace is non-empty,
// the namespace is prepended:
//
//	"bar.localhost"          suffix=".localhost" ns="payments" -> "/payments/bar"
//	"payments.bar.localhost" suffix=".localhost" ns="payments" -> "/payments/bar"
//	"bar.localhost"          suffix=".localhost" ns=""         -> "/bar"
func queueFromHost(host, domainSuffix, namespace string) (string, error) {
	h := host
	if i := strings.LastIndex(h, ":"); i >= 0 {
		h = h[:i]
	}
	if !strings.HasSuffix(h, domainSuffix) {
		return "", fmt.Errorf("host %q does not end with domain suffix %q", host, domainSuffix)
	}
	h = strings.TrimSuffix(h, domainSuffix)
	if h == "" {
		return "", fmt.Errorf("host %q has no service name before domain suffix %q", host, domainSuffix)
	}
	parts := strings.Split(h, ".")
	if len(parts) == 1 && namespace != "" {
		parts = append([]string{namespace}, parts...)
	}
	return "/" + strings.Join(parts, "/"), nil
}
