package async

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"path"
	"strings"
	"sync"
	"time"

	"github.com/shiblon/entroq"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/noop"
	"google.golang.org/grpc/metadata"
)

const defaultRequestTimeout = 30 * time.Second

// Sender is an http.Handler that accepts outgoing HTTP calls from a local
// service and routes them through EntroQ task queues. Each request is
// translated into a task on the target queue, and the sender blocks waiting
// for a response task to appear on an ephemeral per-request response queue.
//
// Path routing: the first path segment names the target queue; the rest is
// forwarded as the request path. For example, a request to /svc-b/process
// enqueues a task on queue "svc-b" with forwarded path "/process".
//
// # Delivery semantics
//
// Delivery is at-least-once. The receiver worker claims a request task,
// calls the upstream HTTP handler, inserts a response task, then deletes the
// request task. If the receiver crashes after the HTTP call but before the
// delete, the request task expires and is re-claimed, causing the upstream
// handler to be called again. Upstream handlers must therefore be idempotent:
// given the same request payload they must perform the same work and return
// an equivalent response.
//
// Any unique tokens the caller needs (idempotency keys, nonces, correlation
// IDs) should be generated by the caller and embedded in the request payload
// before the task is enqueued. Generating them inside the handler produces a
// different value on each replay, which defeats idempotency.
//
// If the sender disconnects or crashes after enqueuing the request but before
// the response arrives, the upstream still does the work and inserts a
// response task. That response task sits on the ephemeral response queue until
// GC collects it (keyed by the expiry timestamp in the queue name). The
// upstream work cannot be un-done; callers that care about exactly-once
// semantics must track completion state themselves.
type Sender struct {
	sync.Mutex

	eq             *entroq.EntroQ
	myQueue        string
	requestTimeout time.Duration
	addr           string
	mp             metric.MeterProvider
	tlsConfig      *tls.Config

	srv         *http.Server // set by Serve; Close uses it for shutdown
	metricsOnce sync.Once

	// OTel instruments, initialized on first use.
	metricInflight metric.Int64UpDownCounter
	metricHandled  metric.Int64Counter
	metricDuration metric.Float64Histogram
}

// SenderOption configures a Sender.
type SenderOption func(*Sender)

// WithSenderRequestTimeout sets how long ServeHTTP waits for a response task before
// returning 504. Also used as the exp= value in the response queue name.
// Defaults to 30 seconds.
func WithSenderRequestTimeout(d time.Duration) SenderOption {
	return func(s *Sender) {
		s.requestTimeout = d
	}
}

// WithSenderMeterProvider sets the OTel MeterProvider used to create instruments.
// Defaults to metric.NewNoopMeterProvider() if not set.
func WithSenderMeterProvider(mp metric.MeterProvider) SenderOption {
	return func(s *Sender) {
		s.mp = mp
	}
}

// WithSenderTLSConfig sets the TLS configuration for the sender's HTTP server.
// If provided, the server will use this config for mTLS and identity extraction.
func WithSenderTLSConfig(cfg *tls.Config) SenderOption {
	return func(s *Sender) {
		s.tlsConfig = cfg
	}
}

// NewSender creates a Sender that listens on addr and uses myQueue as the
// namespace for response queues.
func NewSender(eq *entroq.EntroQ, addr, myQueue string, opts ...SenderOption) *Sender {
	s := &Sender{
		eq:             eq,
		addr:           addr,
		myQueue:        myQueue,
		requestTimeout: defaultRequestTimeout,
		mp:             noop.NewMeterProvider(),
	}
	for _, o := range opts {
		o(s)
	}
	// Initialize metrics eagerly so ServeHTTP is safe to call without Serve.
	// WithSenderMeterProvider must be applied before NewSender returns, so this
	// captures the final provider.
	if err := s.initMetrics(); err != nil {
		log.Printf("sender init metrics: %v", err)
	}
	return s
}

// initMetrics creates OTel instruments from the configured MeterProvider.
// Safe to call multiple times; only runs once.
func (s *Sender) initMetrics() error {
	var initErr error
	s.metricsOnce.Do(func() {
		initErr = s.doInitMetrics()
	})
	return initErr
}

func (s *Sender) doInitMetrics() error {
	m := s.mp.Meter("entroq/async/sender")
	var err error
	if s.metricInflight, err = m.Int64UpDownCounter("sender.inflight",
		metric.WithDescription("Number of in-flight requests currently being processed."),
	); err != nil {
		return fmt.Errorf("sender inflight counter: %w", err)
	}
	if s.metricHandled, err = m.Int64Counter("sender.handled_total",
		metric.WithDescription("Total number of requests handled by the sender."),
	); err != nil {
		return fmt.Errorf("sender handled counter: %w", err)
	}
	if s.metricDuration, err = m.Float64Histogram("sender.duration_seconds",
		metric.WithDescription("Request round-trip duration in seconds."),
		metric.WithUnit("s"),
	); err != nil {
		return fmt.Errorf("sender duration histogram: %w", err)
	}
	return nil
}

// Close gracefully shuts down the sender. It waits for all in-flight requests
// to complete (or ctx to expire), then shuts down the HTTP server.
//
// After Close returns, Run or Serve will also return.
func (s *Sender) Close(ctx context.Context) error {
	s.Lock()
	srv := s.srv
	s.Unlock()

	// Sequence: stop accepting new connections, then drain existing responses
	// from the queue (finish them out if possible).
	if err := srv.Shutdown(ctx); err != nil {
		return fmt.Errorf("sender shutdown: %w", err)
	}
	return nil
}

// Run starts the HTTP server on the address provided to NewSender and blocks
// until Close is called.
func (s *Sender) Run(ctx context.Context) error {
	lis, err := net.Listen("tcp", s.addr)
	if err != nil {
		return fmt.Errorf("sender listen: %w", err)
	}
	return s.Serve(ctx, lis)
}

// Serve starts the HTTP server on an already-open listener and blocks until
// Close is called. Useful when the caller needs to know the bound address
// before starting (e.g. when using ":0" for a random port in tests).
func (s *Sender) Serve(ctx context.Context, lis net.Listener) error {
	if err := s.initMetrics(); err != nil {
		return err
	}

	s.Lock()
	s.srv = &http.Server{
		Handler:   s,
		TLSConfig: s.tlsConfig,
	}
	srv := s.srv
	s.Unlock()

	var err error
	if s.tlsConfig != nil {
		err = srv.ServeTLS(lis, "", "")
	} else {
		err = srv.Serve(lis)
	}

	if err != nil && !errors.Is(err, http.ErrServerClosed) {
		return fmt.Errorf("sender serve: %w", err)
	}
	return nil
}

// ServeHTTP handles an outgoing request from the local service. It translates
// it into an Envelope task, enqueues it, then blocks until a Response task
// arrives on the ephemeral per-request response queue.
func (s *Sender) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	start := time.Now()

	s.metricInflight.Add(r.Context(), 1)
	defer func() {
		s.metricInflight.Add(r.Context(), -1)
		s.metricHandled.Add(r.Context(), 1)
		s.metricDuration.Record(r.Context(), time.Since(start).Seconds())
	}()

	ctx := r.Context()

	// If we have TLS peer certificates, use the Common Name as the identity
	// for the underlying EntroQ calls. This allows the backend to perform
	// authorization based on the mTLS identity of the caller.
	if r.TLS != nil && len(r.TLS.PeerCertificates) > 0 {
		cn := r.TLS.PeerCertificates[0].Subject.CommonName
		ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "mTLS "+cn)
	}

	targetQueue, forwardPath, err := parsePath(r.URL.Path)
	if err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}

	// TODO: add MaxBodySize option and cap with http.MaxBytesReader to avoid
	// memory pressure from large payloads. Return 413 when exceeded.
	body, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, fmt.Sprintf("read request body: %v", err), http.StatusBadRequest)
		return
	}

	headers := make(map[string]string, len(r.Header))
	for k := range r.Header {
		headers[k] = r.Header.Get(k)
	}

	expiry := time.Now().Add(s.requestTimeout)
	responseQueue := path.Join(s.myQueue, "response",
		fmt.Sprintf("exp=%d", expiry.Unix()),
		entroq.GenHex16())

	env := Envelope{
		Method:        r.Method,
		Path:          forwardPath,
		Headers:       headers,
		Body:          json.RawMessage(body),
		ResponseQueue: responseQueue,
	}
	envValue, err := json.Marshal(env)
	if err != nil {
		http.Error(w, fmt.Sprintf("marshal envelope: %v", err), http.StatusInternalServerError)
		return
	}

	if _, err := s.eq.Modify(ctx,
		entroq.InsertingInto(targetQueue, entroq.WithRawValue(envValue)),
	); err != nil {
		http.Error(w, fmt.Sprintf("enqueue task: %v", err), http.StatusBadGateway)
		return
	}

	// Block until the response arrives, the request timeout elapses, or the
	// caller disconnects. WithTimeout derives from ctx so whichever deadline
	// is sooner wins.
	claimCtx, cancel := context.WithTimeout(ctx, s.requestTimeout)
	defer cancel()
	task, err := s.eq.Claim(claimCtx, entroq.From(responseQueue))
	if err != nil {
		log.Printf("sender await response on %s: %v", responseQueue, err)
		http.Error(w, fmt.Sprintf("await response: %v", err), http.StatusGatewayTimeout)
		return
	}
	defer s.deleteTask(ctx, task)

	resp, err := entroq.GetValue[Response](task)
	if err != nil {
		http.Error(w, fmt.Sprintf("unmarshal response: %v", err), http.StatusBadGateway)
		return
	}

	for k, v := range resp.Headers {
		w.Header().Set(k, v)
	}
	w.WriteHeader(resp.StatusCode)
	if _, err := w.Write(resp.Body); err != nil {
		log.Printf("sender write response: %v", err)
	}
}

// deleteTask removes a task from EntroQ, logging on failure. Used for
// response queue cleanup after the response has been read.
func (s *Sender) deleteTask(ctx context.Context, task *entroq.Task) {
	if _, err := s.eq.Modify(ctx, task.Delete()); err != nil {
		log.Printf("sender delete task %v: %v (GC will clean up)", task.ID, err)
	}
}

// parsePath splits an incoming path into the target queue name and the
// forwarded request path. The first non-empty path segment is the queue name;
// the remainder (with leading slash) is the forwarded path.
//
// "/svc-b/process" -> ("svc-b", "/process", nil)
// "/svc-b"         -> ("svc-b", "/",        nil)
//
// TODO: first-segment routing doesn't compose with hierarchical queue names
// (e.g. /ns=org/svc-b). A future convention (double-slash delimiter, header,
// etc.) could support namespaced targets, which would be useful for authz groups.
func parsePath(path string) (queue, forwardPath string, err error) {
	path = strings.TrimPrefix(path, "/")
	queue, rest, _ := strings.Cut(path, "/")
	if queue == "" {
		return "", "", fmt.Errorf("path must begin with a target queue name")
	}
	return queue, "/" + rest, nil
}
