package async

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"log/slog"
	"net"
	"net/http"
	"path"
	"strings"
	"sync"
	"time"

	"github.com/shiblon/entroq"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/noop"
	"google.golang.org/grpc/metadata"
)

const defaultRequestTimeout = 30 * time.Second

// Sender is an http.Handler that accepts outgoing HTTP calls from a local
// service and routes them through EntroQ task queues. Each request is
// translated into a task on the target queue, and the sender blocks waiting
// for a response task to appear on an ephemeral per-request response queue.
//
// Path routing: the first path segment names the target queue; the rest is
// forwarded as the request path. For example, a request to /svc-b/process
// enqueues a task on queue "svc-b" with forwarded path "/process".
//
// # Delivery semantics
//
// Delivery is at-least-once. The receiver worker claims a request task,
// calls the upstream HTTP handler, inserts a response task, then deletes the
// request task. If the receiver crashes after the HTTP call but before the
// delete, the request task expires and is re-claimed, causing the upstream
// handler to be called again. Upstream handlers must therefore be idempotent:
// given the same request payload they must perform the same work and return
// an equivalent response.
//
// Any unique tokens the caller needs (idempotency keys, nonces, correlation
// IDs) should be generated by the caller and embedded in the request payload
// before the task is enqueued. Generating them inside the handler produces a
// different value on each replay, which defeats idempotency.
//
// If the sender disconnects or crashes after enqueuing the request but before
// the response arrives, the upstream still does the work and inserts a
// response task. That response task sits on the ephemeral response queue until
// GC collects it (keyed by the expiry timestamp in the queue name). The
// upstream work cannot be un-done; callers that care about exactly-once
// semantics must track completion state themselves.
type Sender struct {
	sync.Mutex

	eq             *entroq.EntroQ
	domainSuffix   string
	namespace      string
	name           string
	auditLog       *slog.Logger
	requestTimeout time.Duration
	addr           string
	mp             metric.MeterProvider
	tlsConfig      *tls.Config

	srv         *http.Server // set by Serve; Close uses it for shutdown
	metricsOnce sync.Once

	// OTel instruments, initialized on first use.
	metricInflight metric.Int64UpDownCounter
	metricHandled  metric.Int64Counter
	metricDuration metric.Float64Histogram
}

// SenderOption configures a Sender.
type SenderOption func(*Sender)

// WithSenderRequestTimeout sets how long ServeHTTP waits for a response task before
// returning 504. Also used as the exp= value in the response queue name.
// Defaults to 30 seconds.
func WithSenderRequestTimeout(d time.Duration) SenderOption {
	return func(s *Sender) {
		s.requestTimeout = d
	}
}

// WithSenderMeterProvider sets the OTel MeterProvider used to create instruments.
// Defaults to metric.NewNoopMeterProvider() if not set.
func WithSenderMeterProvider(mp metric.MeterProvider) SenderOption {
	return func(s *Sender) {
		s.mp = mp
	}
}

// WithSenderTLSConfig sets the TLS configuration for the sender's HTTP server.
// If provided, the server will use this config for mTLS and identity extraction.
func WithSenderTLSConfig(cfg *tls.Config) SenderOption {
	return func(s *Sender) {
		s.tlsConfig = cfg
	}
}


// WithSenderDomainSuffix sets the domain suffix stripped from the Host header
// to derive the target service name. Defaults to ".localhost".
func WithSenderDomainSuffix(suffix string) SenderOption {
	return func(s *Sender) {
		s.domainSuffix = suffix
	}
}

// WithSenderNamespace sets the default namespace prepended to single-label
// host names. When the host resolves to a single service name (e.g. "bar"
// from "bar.localhost"), the namespace is prepended to form "ns/bar".
// Has no effect when the host already encodes a namespace (e.g. "ns.bar.localhost").
func WithSenderNamespace(ns string) SenderOption {
	return func(s *Sender) {
		s.namespace = ns
	}
}

// WithSenderName sets the service identity used in audit log entries as the
// "from" field. Typically the service's own queue prefix (e.g. "payments/svc-a").
// Has no effect when audit logging is disabled.
func WithSenderName(name string) SenderOption {
	return func(s *Sender) {
		s.name = name
	}
}

// WithSenderAuditLogger enables structured audit logging for every request
// the sender mediates. When set, three events are emitted per request:
// request_enqueued (on task insert), and response_received (on task claim).
// Payload content is never logged; only queue names, method, path, status,
// and timing are recorded.
func WithSenderAuditLogger(l *slog.Logger) SenderOption {
	return func(s *Sender) {
		s.auditLog = l
	}
}

// NewSender creates a Sender that listens on addr and routes outbound requests
// by extracting the target service from the Host header of incoming requests.
func NewSender(eq *entroq.EntroQ, addr string, opts ...SenderOption) *Sender {
	s := &Sender{
		eq:             eq,
		addr:           addr,
		domainSuffix:   ".localhost",
		requestTimeout: defaultRequestTimeout,
		mp:             noop.NewMeterProvider(),
	}
	for _, o := range opts {
		o(s)
	}
	// Initialize metrics eagerly so ServeHTTP is safe to call without Serve.
	// WithSenderMeterProvider must be applied before NewSender returns, so this
	// captures the final provider.
	if err := s.initMetrics(); err != nil {
		log.Printf("sender init metrics: %v", err)
	}
	return s
}

// initMetrics creates OTel instruments from the configured MeterProvider.
// Safe to call multiple times; only runs once.
func (s *Sender) initMetrics() error {
	var initErr error
	s.metricsOnce.Do(func() {
		initErr = s.doInitMetrics()
	})
	return initErr
}

func (s *Sender) doInitMetrics() error {
	m := s.mp.Meter("entroq/async/sender")
	var err error
	if s.metricInflight, err = m.Int64UpDownCounter("sender.inflight",
		metric.WithDescription("Number of in-flight requests currently being processed."),
	); err != nil {
		return fmt.Errorf("sender inflight counter: %w", err)
	}
	if s.metricHandled, err = m.Int64Counter("sender.handled_total",
		metric.WithDescription("Total number of requests handled by the sender."),
	); err != nil {
		return fmt.Errorf("sender handled counter: %w", err)
	}
	if s.metricDuration, err = m.Float64Histogram("sender.duration_seconds",
		metric.WithDescription("Request round-trip duration in seconds."),
		metric.WithUnit("s"),
	); err != nil {
		return fmt.Errorf("sender duration histogram: %w", err)
	}
	return nil
}

// Close gracefully shuts down the sender. It waits for all in-flight requests
// to complete (or ctx to expire), then shuts down the HTTP server.
//
// After Close returns, Run or Serve will also return.
func (s *Sender) Close(ctx context.Context) error {
	s.Lock()
	srv := s.srv
	s.Unlock()

	// Sequence: stop accepting new connections, then drain existing responses
	// from the queue (finish them out if possible).
	if err := srv.Shutdown(ctx); err != nil {
		return fmt.Errorf("sender shutdown: %w", err)
	}
	return nil
}

// Run starts the HTTP server on the address provided to NewSender and blocks
// until Close is called.
func (s *Sender) Run(ctx context.Context) error {
	lis, err := net.Listen("tcp", s.addr)
	if err != nil {
		return fmt.Errorf("sender listen: %w", err)
	}
	return s.Serve(ctx, lis)
}

// Serve starts the HTTP server on an already-open listener and blocks until
// Close is called. Useful when the caller needs to know the bound address
// before starting (e.g. when using ":0" for a random port in tests).
func (s *Sender) Serve(ctx context.Context, lis net.Listener) error {
	if err := s.initMetrics(); err != nil {
		return err
	}

	s.Lock()
	s.srv = &http.Server{
		Handler:   s,
		TLSConfig: s.tlsConfig,
	}
	srv := s.srv
	s.Unlock()

	var err error
	if s.tlsConfig != nil {
		err = srv.ServeTLS(lis, "", "")
	} else {
		err = srv.Serve(lis)
	}

	if err != nil && !errors.Is(err, http.ErrServerClosed) {
		return fmt.Errorf("sender serve: %w", err)
	}
	return nil
}

// ServeHTTP handles an outgoing request from the local service. It translates
// it into an Envelope task, enqueues it, then blocks until a Response task
// arrives on the ephemeral per-request response queue.
func (s *Sender) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	start := time.Now()

	s.metricInflight.Add(r.Context(), 1)
	defer func() {
		s.metricInflight.Add(r.Context(), -1)
		s.metricHandled.Add(r.Context(), 1)
		s.metricDuration.Record(r.Context(), time.Since(start).Seconds())
	}()

	ctx := r.Context()

	// If we have TLS peer certificates, use the Common Name as the identity
	// for the underlying EntroQ calls. This allows the backend to perform
	// authorization based on the mTLS identity of the caller.
	if r.TLS != nil && len(r.TLS.PeerCertificates) > 0 {
		cn := r.TLS.PeerCertificates[0].Subject.CommonName
		ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "mTLS "+cn)
	}

	// Reject streaming protocols early with a clear explanation.
	// eqlink buffers the full request and response as task payloads; streaming
	// is fundamentally incompatible with this transport model.
	if r.Header.Get("Upgrade") != "" {
		http.Error(w, "eqlink does not support protocol upgrades (WebSocket, HTTP/2 upgrade, etc.); this transport is request-response only", http.StatusNotImplemented)
		return
	}
	if strings.Contains(r.Header.Get("Accept"), "text/event-stream") {
		http.Error(w, "eqlink does not support server-sent events; this transport is request-response only", http.StatusNotImplemented)
		return
	}

	queuePrefix, err := queueFromHost(r.Host, s.domainSuffix, s.namespace)
	if err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}
	targetInbox := path.Join(queuePrefix, "inbox")
	// RequestURI includes the query string; Path alone would drop it.
	forwardPath := r.URL.RequestURI()

	// TODO: add MaxBodySize option and cap with http.MaxBytesReader to avoid
	// memory pressure from large payloads. Return 413 when exceeded.
	body, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, fmt.Sprintf("read request body: %v", err), http.StatusBadRequest)
		return
	}

	headers := copyHeaders(r.Header)

	expiry := time.Now().Add(s.requestTimeout)
	responseQueue := path.Join(queuePrefix, "response",
		fmt.Sprintf("exp=%d", expiry.Unix()),
		entroq.GenHex16())

	env := Envelope{
		Method:        r.Method,
		Path:          forwardPath,
		Headers:       headers,
		Body:          json.RawMessage(body),
		ResponseQueue: responseQueue,
	}
	envValue, err := json.Marshal(env)
	if err != nil {
		http.Error(w, fmt.Sprintf("marshal envelope: %v", err), http.StatusInternalServerError)
		return
	}

	if _, err := s.eq.Modify(ctx,
		entroq.InsertingInto(targetInbox, entroq.WithRawValue(envValue)),
	); err != nil {
		log.Printf("sender enqueue to %s: %v", targetInbox, err)
		http.Error(w, fmt.Sprintf("enqueue task: %v", err), http.StatusBadGateway)
		return
	}
	if s.auditLog != nil {
		s.auditLog.LogAttrs(ctx, slog.LevelInfo, "request_enqueued",
			slog.String("from", s.name),
			slog.String("to", targetInbox),
			slog.String("method", r.Method),
			slog.String("path", r.URL.Path),
			slog.String("response_queue", responseQueue),
		)
	}

	// Block until the response arrives, the request timeout elapses, or the
	// caller disconnects. WithTimeout derives from ctx so whichever deadline
	// is sooner wins.
	claimCtx, cancel := context.WithTimeout(ctx, s.requestTimeout)
	defer cancel()
	task, err := s.eq.Claim(claimCtx, entroq.From(responseQueue))
	if err != nil {
		log.Printf("sender await response on %s (timeout=%v): %v", responseQueue, s.requestTimeout, err)
		http.Error(w, fmt.Sprintf("await response: %v", err), http.StatusGatewayTimeout)
		return
	}
	defer s.deleteTask(ctx, task)

	resp, err := entroq.GetValue[Response](task)
	if err != nil {
		http.Error(w, fmt.Sprintf("unmarshal response: %v", err), http.StatusBadGateway)
		return
	}
	if s.auditLog != nil {
		s.auditLog.LogAttrs(ctx, slog.LevelInfo, "response_received",
			slog.String("response_queue", responseQueue),
			slog.Int("status_code", resp.StatusCode),
			slog.Float64("duration_s", time.Since(start).Seconds()),
		)
	}

	for k, vs := range resp.Headers {
		for _, v := range vs {
			w.Header().Add(k, v)
		}
	}
	w.WriteHeader(resp.StatusCode)
	if _, err := w.Write(resp.Body); err != nil {
		log.Printf("sender write response: %v", err)
	}
}

// deleteTask removes a task from EntroQ, logging on failure. Used for
// response queue cleanup after the response has been read.
func (s *Sender) deleteTask(ctx context.Context, task *entroq.Task) {
	if _, err := s.eq.Modify(ctx, task.Delete()); err != nil {
		log.Printf("sender delete task %v: %v (GC will clean up)", task.ID, err)
	}
}

// queueFromHost derives a queue prefix from an HTTP Host header value.
// It strips the port, then the configured domain suffix, and maps the remaining
// dot-separated labels left-to-right to a slash-separated queue path.
// The result always starts with "/" to match EntroQ queue naming conventions.
//
// If only one label remains after suffix stripping and namespace is non-empty,
// the namespace is prepended:
//
//	"bar.localhost"          suffix=".localhost" ns="payments" -> "/payments/bar"
//	"payments.bar.localhost" suffix=".localhost" ns="payments" -> "/payments/bar"
//	"bar.localhost"          suffix=".localhost" ns=""         -> "/bar"
func queueFromHost(host, domainSuffix, namespace string) (string, error) {
	h := host
	if i := strings.LastIndex(h, ":"); i >= 0 {
		h = h[:i]
	}
	if !strings.HasSuffix(h, domainSuffix) {
		return "", fmt.Errorf("host %q does not end with domain suffix %q", host, domainSuffix)
	}
	h = strings.TrimSuffix(h, domainSuffix)
	if h == "" {
		return "", fmt.Errorf("host %q has no service name before domain suffix %q", host, domainSuffix)
	}
	parts := strings.Split(h, ".")
	if len(parts) == 1 && namespace != "" {
		parts = append([]string{namespace}, parts...)
	}
	return "/" + strings.Join(parts, "/"), nil
}
