{{- $backend := .Values.entroq.backend.type -}}
{{- if and .Values.entroq.enabled (eq $backend "postgres") (not .Values.entroq.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: entroq-system
  labels:
    {{- include "entroq.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.entroq.postgres.password | quote }}
{{- end }}
{{- if and .Values.entroq.enabled (eq $backend "redis") (not .Values.entroq.redis.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis
  namespace: entroq-system
  labels:
    {{- include "entroq.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.entroq.redis.password | quote }}
{{- end }}
