// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: entroq.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ActionType int32

const (
	ActionType_CLAIM  ActionType = 0
	ActionType_DELETE ActionType = 1
	ActionType_CHANGE ActionType = 2
	ActionType_DEPEND ActionType = 3
	ActionType_DETAIL ActionType = 4
	ActionType_INSERT ActionType = 5
	ActionType_READ   ActionType = 6
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "CLAIM",
		1: "DELETE",
		2: "CHANGE",
		3: "DEPEND",
		4: "DETAIL",
		5: "INSERT",
		6: "READ",
	}
	ActionType_value = map[string]int32{
		"CLAIM":  0,
		"DELETE": 1,
		"CHANGE": 2,
		"DEPEND": 3,
		"DETAIL": 4,
		"INSERT": 5,
		"READ":   6,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_entroq_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_entroq_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{0}
}

// TaskID contains the ID and version of a task. Together these make a unique
// identifier for that task.
type TaskID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Optional queue name. This usually comes from the task itself, so it will
	// be present in most use cases. There are some cases where it will be empty,
	// like when using admin tools with special privileges. Usually you should
	// set this, as Authorization policies will be looking for it to ensure that
	// you are allowed to change, delete, or depend on this ID based on the queue
	// name.
	Queue string `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
}

func (x *TaskID) Reset() {
	*x = TaskID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskID) ProtoMessage() {}

func (x *TaskID) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskID.ProtoReflect.Descriptor instead.
func (*TaskID) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{0}
}

func (x *TaskID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskID) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TaskID) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

// TaskData contains only the data portion of a task. Useful for insertion and for modifying tasks.
type TaskData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the queue for this task.
	Queue string `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// The epoch time in millis when this task becomes available.
	AtMs int64 `protobuf:"varint,2,opt,name=at_ms,json=atMs,proto3" json:"at_ms,omitempty"`
	// The task's JSON payload.
	Value *structpb.Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// An optional ID (UUID) for an inserted task to use.
	// Default is for the backend to assign one, and that is sufficient for many
	// cases. If you desire to make a database entry that *references* a task,
	// however, in that case it can make sense to specify an explicit task ID for
	// insertion (allowing "consume -> db update -> modify" worker cycles to
	// safely update a database entry that references to-be-inserted tasks).
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// Attempt and Err are used to indicate a "retryable error" with a number of
	// times attempted. This is used by the worker, and can be changed during
	// task modification.
	Attempt int32  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Err     string `protobuf:"bytes,6,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *TaskData) Reset() {
	*x = TaskData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskData) ProtoMessage() {}

func (x *TaskData) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskData.ProtoReflect.Descriptor instead.
func (*TaskData) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{1}
}

func (x *TaskData) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskData) GetAtMs() int64 {
	if x != nil {
		return x.AtMs
	}
	return 0
}

func (x *TaskData) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TaskData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskData) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TaskData) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// TaskChange identifies a task by ID and specifies the new data it should contain.
// All fields should be filled in. Empty fields result in deleting data from that field.
type TaskChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldId   *TaskID   `protobuf:"bytes,1,opt,name=old_id,json=oldId,proto3" json:"old_id,omitempty"`
	NewData *TaskData `protobuf:"bytes,2,opt,name=new_data,json=newData,proto3" json:"new_data,omitempty"`
}

func (x *TaskChange) Reset() {
	*x = TaskChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskChange) ProtoMessage() {}

func (x *TaskChange) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskChange.ProtoReflect.Descriptor instead.
func (*TaskChange) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{2}
}

func (x *TaskChange) GetOldId() *TaskID {
	if x != nil {
		return x.OldId
	}
	return nil
}

func (x *TaskChange) GetNewData() *TaskData {
	if x != nil {
		return x.NewData
	}
	return nil
}

// Task is a complete task object, containing IDs, data, and metadata.
type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the queue for this task.
	Queue   string `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// The epoch time in millis when this task becomes available.
	AtMs int64 `protobuf:"varint,4,opt,name=at_ms,json=atMs,proto3" json:"at_ms,omitempty"`
	// The UUID representing the claimant (owner) for this task.
	ClaimantId string `protobuf:"bytes,5,opt,name=claimant_id,json=claimantId,proto3" json:"claimant_id,omitempty"`
	// The task's JSON payload.
	Value *structpb.Value `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	// Epoch times in millis for creation and update of this task.
	CreatedMs  int64 `protobuf:"varint,7,opt,name=created_ms,json=createdMs,proto3" json:"created_ms,omitempty"`
	ModifiedMs int64 `protobuf:"varint,8,opt,name=modified_ms,json=modifiedMs,proto3" json:"modified_ms,omitempty"`
	// The number of times this has been successfully claimed.
	Claims int32 `protobuf:"varint,9,opt,name=claims,proto3" json:"claims,omitempty"`
	// Attempt and Err are used to indicate a "retryable error" with a number of
	// times attempted. This is used by the worker, and can be changed during
	// task modification.
	Attempt int32  `protobuf:"varint,10,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Err     string `protobuf:"bytes,11,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Task) GetAtMs() int64 {
	if x != nil {
		return x.AtMs
	}
	return 0
}

func (x *Task) GetClaimantId() string {
	if x != nil {
		return x.ClaimantId
	}
	return ""
}

func (x *Task) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Task) GetCreatedMs() int64 {
	if x != nil {
		return x.CreatedMs
	}
	return 0
}

func (x *Task) GetModifiedMs() int64 {
	if x != nil {
		return x.ModifiedMs
	}
	return 0
}

func (x *Task) GetClaims() int32 {
	if x != nil {
		return x.Claims
	}
	return 0
}

func (x *Task) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Task) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// QueueStats contains the name of the queue and the number of tasks within it.
type QueueStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumTasks     int32  `protobuf:"varint,2,opt,name=num_tasks,json=numTasks,proto3" json:"num_tasks,omitempty"`
	NumClaimed   int32  `protobuf:"varint,3,opt,name=num_claimed,json=numClaimed,proto3" json:"num_claimed,omitempty"`
	NumAvailable int32  `protobuf:"varint,4,opt,name=num_available,json=numAvailable,proto3" json:"num_available,omitempty"`
	// Maximum claims value for any task in the queue
	// (can help detect tasks that are causing crashes, etc.)
	MaxClaims int32 `protobuf:"varint,5,opt,name=max_claims,json=maxClaims,proto3" json:"max_claims,omitempty"`
	// Number of tasks with a future arrival time and 0 claims.
	NumFuture int32 `protobuf:"varint,6,opt,name=num_future,json=numFuture,proto3" json:"num_future,omitempty"`
}

func (x *QueueStats) Reset() {
	*x = QueueStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStats) ProtoMessage() {}

func (x *QueueStats) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStats.ProtoReflect.Descriptor instead.
func (*QueueStats) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{4}
}

func (x *QueueStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueStats) GetNumTasks() int32 {
	if x != nil {
		return x.NumTasks
	}
	return 0
}

func (x *QueueStats) GetNumClaimed() int32 {
	if x != nil {
		return x.NumClaimed
	}
	return 0
}

func (x *QueueStats) GetNumAvailable() int32 {
	if x != nil {
		return x.NumAvailable
	}
	return 0
}

func (x *QueueStats) GetMaxClaims() int32 {
	if x != nil {
		return x.MaxClaims
	}
	return 0
}

func (x *QueueStats) GetNumFuture() int32 {
	if x != nil {
		return x.NumFuture
	}
	return 0
}

// ClaimRequest is sent to attempt to claim a task from a queue. The claimant ID
// should be unique to the requesting worker (e.g., if multiple workers are in
// the same process, they should all have different claimant IDs assigned).
type ClaimRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The party requesting a task.
	ClaimantId string `protobuf:"bytes,1,opt,name=claimant_id,json=claimantId,proto3" json:"claimant_id,omitempty"`
	// The queue names to claim a task from.
	Queues []string `protobuf:"bytes,2,rep,name=queues,proto3" json:"queues,omitempty"`
	// The duration of the claim, if/once successful.
	DurationMs int64 `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// How long to sleep for a claim (not try claim) between polls. The sleep may be interruptible depending on the backend implementation.
	PollMs int64 `protobuf:"varint,4,opt,name=poll_ms,json=pollMs,proto3" json:"poll_ms,omitempty"`
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimRequest) GetClaimantId() string {
	if x != nil {
		return x.ClaimantId
	}
	return ""
}

func (x *ClaimRequest) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *ClaimRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ClaimRequest) GetPollMs() int64 {
	if x != nil {
		return x.PollMs
	}
	return 0
}

// ClaimResponse is returned when a claim is fulfilled or becomes obviously impossible.
//
// For TryClaim calls, if no task is available, the task will be empty and the
// status code sent to the client will be OK.
//
// For Claim calls, the lack of a task is an error, usually a timeout or
// cancelation.
type ClaimResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// DocID identifies a specific version of a doc.
type DocID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version   int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DocID) Reset() {
	*x = DocID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocID) ProtoMessage() {}

func (x *DocID) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocID.ProtoReflect.Descriptor instead.
func (*DocID) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{7}
}

func (x *DocID) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DocID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocID) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// DocData holds the data portion of a doc, used for insertions. The created_ms
// and modified_ms fields are used only for journal replay; leave them zero for
// normal insertions.
type DocData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace    string          `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id           string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Key          string          `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	SecondaryKey string          `protobuf:"bytes,4,opt,name=secondary_key,json=secondaryKey,proto3" json:"secondary_key,omitempty"`
	Content      *structpb.Value `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedMs    int64           `protobuf:"varint,6,opt,name=created_ms,json=createdMs,proto3" json:"created_ms,omitempty"`
	ModifiedMs   int64           `protobuf:"varint,7,opt,name=modified_ms,json=modifiedMs,proto3" json:"modified_ms,omitempty"`
}

func (x *DocData) Reset() {
	*x = DocData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocData) ProtoMessage() {}

func (x *DocData) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocData.ProtoReflect.Descriptor instead.
func (*DocData) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{8}
}

func (x *DocData) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DocData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DocData) GetSecondaryKey() string {
	if x != nil {
		return x.SecondaryKey
	}
	return ""
}

func (x *DocData) GetContent() *structpb.Value {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DocData) GetCreatedMs() int64 {
	if x != nil {
		return x.CreatedMs
	}
	return 0
}

func (x *DocData) GetModifiedMs() int64 {
	if x != nil {
		return x.ModifiedMs
	}
	return 0
}

// DocChange identifies a doc by DocID and provides updated data. Only content
// from new_data is applied; keys are immutable after creation.
type DocChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldId   *DocID   `protobuf:"bytes,1,opt,name=old_id,json=oldId,proto3" json:"old_id,omitempty"`
	NewData *DocData `protobuf:"bytes,2,opt,name=new_data,json=newData,proto3" json:"new_data,omitempty"`
}

func (x *DocChange) Reset() {
	*x = DocChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocChange) ProtoMessage() {}

func (x *DocChange) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocChange.ProtoReflect.Descriptor instead.
func (*DocChange) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{9}
}

func (x *DocChange) GetOldId() *DocID {
	if x != nil {
		return x.OldId
	}
	return nil
}

func (x *DocChange) GetNewData() *DocData {
	if x != nil {
		return x.NewData
	}
	return nil
}

// Doc is a complete doc object with identity, data, and metadata.
type Doc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace    string          `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id           string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version      int32           `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Claimant     string          `protobuf:"bytes,4,opt,name=claimant,proto3" json:"claimant,omitempty"`
	AtMs         int64           `protobuf:"varint,5,opt,name=at_ms,json=atMs,proto3" json:"at_ms,omitempty"`
	Key          string          `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	SecondaryKey string          `protobuf:"bytes,7,opt,name=secondary_key,json=secondaryKey,proto3" json:"secondary_key,omitempty"`
	Content      *structpb.Value `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	CreatedMs    int64           `protobuf:"varint,9,opt,name=created_ms,json=createdMs,proto3" json:"created_ms,omitempty"`
	ModifiedMs   int64           `protobuf:"varint,10,opt,name=modified_ms,json=modifiedMs,proto3" json:"modified_ms,omitempty"`
}

func (x *Doc) Reset() {
	*x = Doc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doc) ProtoMessage() {}

func (x *Doc) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doc.ProtoReflect.Descriptor instead.
func (*Doc) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{10}
}

func (x *Doc) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Doc) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Doc) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Doc) GetClaimant() string {
	if x != nil {
		return x.Claimant
	}
	return ""
}

func (x *Doc) GetAtMs() int64 {
	if x != nil {
		return x.AtMs
	}
	return 0
}

func (x *Doc) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Doc) GetSecondaryKey() string {
	if x != nil {
		return x.SecondaryKey
	}
	return ""
}

func (x *Doc) GetContent() *structpb.Value {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Doc) GetCreatedMs() int64 {
	if x != nil {
		return x.CreatedMs
	}
	return 0
}

func (x *Doc) GetModifiedMs() int64 {
	if x != nil {
		return x.ModifiedMs
	}
	return 0
}

// DocQuery describes a listing request for docs in a namespace. If ids is
// non-empty, only those docs are returned (key range and limit are ignored).
// Otherwise, key_start and key_end form a half-open range [key_start, key_end)
// on key_primary; leaving key_end empty lists from key_start onward.
type DocQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace  string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	KeyStart   string   `protobuf:"bytes,2,opt,name=key_start,json=keyStart,proto3" json:"key_start,omitempty"`
	KeyEnd     string   `protobuf:"bytes,3,opt,name=key_end,json=keyEnd,proto3" json:"key_end,omitempty"`
	Limit      int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	OmitValues bool     `protobuf:"varint,5,opt,name=omit_values,json=omitValues,proto3" json:"omit_values,omitempty"`
	Ids        []string `protobuf:"bytes,6,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DocQuery) Reset() {
	*x = DocQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocQuery) ProtoMessage() {}

func (x *DocQuery) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocQuery.ProtoReflect.Descriptor instead.
func (*DocQuery) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{11}
}

func (x *DocQuery) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DocQuery) GetKeyStart() string {
	if x != nil {
		return x.KeyStart
	}
	return ""
}

func (x *DocQuery) GetKeyEnd() string {
	if x != nil {
		return x.KeyEnd
	}
	return ""
}

func (x *DocQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DocQuery) GetOmitValues() bool {
	if x != nil {
		return x.OmitValues
	}
	return false
}

func (x *DocQuery) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// DocClaim describes an atomic all-or-nothing claim of docs in a namespace.
// All docs sharing the given key are claimed together.
type DocClaim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace  string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Claimant   string `protobuf:"bytes,2,opt,name=claimant,proto3" json:"claimant,omitempty"`
	Key        string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	DurationMs int64  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
}

func (x *DocClaim) Reset() {
	*x = DocClaim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocClaim) ProtoMessage() {}

func (x *DocClaim) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocClaim.ProtoReflect.Descriptor instead.
func (*DocClaim) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{12}
}

func (x *DocClaim) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DocClaim) GetClaimant() string {
	if x != nil {
		return x.Claimant
	}
	return ""
}

func (x *DocClaim) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DocClaim) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// DocsRequest asks for a listing of docs matching a query.
type DocsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *DocQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *DocsRequest) Reset() {
	*x = DocsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsRequest) ProtoMessage() {}

func (x *DocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsRequest.ProtoReflect.Descriptor instead.
func (*DocsRequest) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{13}
}

func (x *DocsRequest) GetQuery() *DocQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// DocsResponse contains the docs returned by a Docs call.
type DocsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Docs []*Doc `protobuf:"bytes,1,rep,name=docs,proto3" json:"docs,omitempty"`
}

func (x *DocsResponse) Reset() {
	*x = DocsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsResponse) ProtoMessage() {}

func (x *DocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsResponse.ProtoReflect.Descriptor instead.
func (*DocsResponse) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{14}
}

func (x *DocsResponse) GetDocs() []*Doc {
	if x != nil {
		return x.Docs
	}
	return nil
}

// ClaimDocsRequest asks to atomically claim a set of docs.
type ClaimDocsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimQuery *DocClaim `protobuf:"bytes,1,opt,name=claim_query,json=claimQuery,proto3" json:"claim_query,omitempty"`
}

func (x *ClaimDocsRequest) Reset() {
	*x = ClaimDocsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimDocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimDocsRequest) ProtoMessage() {}

func (x *ClaimDocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimDocsRequest.ProtoReflect.Descriptor instead.
func (*ClaimDocsRequest) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{15}
}

func (x *ClaimDocsRequest) GetClaimQuery() *DocClaim {
	if x != nil {
		return x.ClaimQuery
	}
	return nil
}

// ClaimDocsResponse contains the docs claimed by a ClaimDocs call.
// A dependency error (missing or already-claimed docs) comes through as
// gRPC's NOT_FOUND code with ModifyDep details carrying doc_id fields.
type ClaimDocsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Docs []*Doc `protobuf:"bytes,1,rep,name=docs,proto3" json:"docs,omitempty"`
}

func (x *ClaimDocsResponse) Reset() {
	*x = ClaimDocsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimDocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimDocsResponse) ProtoMessage() {}

func (x *ClaimDocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimDocsResponse.ProtoReflect.Descriptor instead.
func (*ClaimDocsResponse) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{16}
}

func (x *ClaimDocsResponse) GetDocs() []*Doc {
	if x != nil {
		return x.Docs
	}
	return nil
}

// ModifyRequest sends a request to modify a set of tasks with given
// dependencies. It is performed in a transaction, in which either all
// suggested modifications succeed and all dependencies are satisfied, or
// nothing is committed at all. A failure due to dependencies (in any
// of changes, deletes, or inserts) will be permanent.
//
// All successful changes will cause the requester to become the claimant.
type ModifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimantId string        `protobuf:"bytes,1,opt,name=claimant_id,json=claimantId,proto3" json:"claimant_id,omitempty"`
	Inserts    []*TaskData   `protobuf:"bytes,2,rep,name=inserts,proto3" json:"inserts,omitempty"`
	Changes    []*TaskChange `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	Deletes    []*TaskID     `protobuf:"bytes,4,rep,name=deletes,proto3" json:"deletes,omitempty"`
	Depends    []*TaskID     `protobuf:"bytes,5,rep,name=depends,proto3" json:"depends,omitempty"`
	DocInserts []*DocData    `protobuf:"bytes,6,rep,name=doc_inserts,json=docInserts,proto3" json:"doc_inserts,omitempty"`
	DocChanges []*DocChange  `protobuf:"bytes,7,rep,name=doc_changes,json=docChanges,proto3" json:"doc_changes,omitempty"`
	DocDeletes []*DocID      `protobuf:"bytes,8,rep,name=doc_deletes,json=docDeletes,proto3" json:"doc_deletes,omitempty"`
	DocDepends []*DocID      `protobuf:"bytes,9,rep,name=doc_depends,json=docDepends,proto3" json:"doc_depends,omitempty"`
}

func (x *ModifyRequest) Reset() {
	*x = ModifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyRequest) ProtoMessage() {}

func (x *ModifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyRequest.ProtoReflect.Descriptor instead.
func (*ModifyRequest) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{17}
}

func (x *ModifyRequest) GetClaimantId() string {
	if x != nil {
		return x.ClaimantId
	}
	return ""
}

func (x *ModifyRequest) GetInserts() []*TaskData {
	if x != nil {
		return x.Inserts
	}
	return nil
}

func (x *ModifyRequest) GetChanges() []*TaskChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ModifyRequest) GetDeletes() []*TaskID {
	if x != nil {
		return x.Deletes
	}
	return nil
}

func (x *ModifyRequest) GetDepends() []*TaskID {
	if x != nil {
		return x.Depends
	}
	return nil
}

func (x *ModifyRequest) GetDocInserts() []*DocData {
	if x != nil {
		return x.DocInserts
	}
	return nil
}

func (x *ModifyRequest) GetDocChanges() []*DocChange {
	if x != nil {
		return x.DocChanges
	}
	return nil
}

func (x *ModifyRequest) GetDocDeletes() []*DocID {
	if x != nil {
		return x.DocDeletes
	}
	return nil
}

func (x *ModifyRequest) GetDocDepends() []*DocID {
	if x != nil {
		return x.DocDepends
	}
	return nil
}

// ModifyResponse returns inserted and updated tasks and docs when successful.
// A dependency error (which is permanent) comes through as gRPC's NOT_FOUND code.
type ModifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inserted     []*Task `protobuf:"bytes,1,rep,name=inserted,proto3" json:"inserted,omitempty"`
	Changed      []*Task `protobuf:"bytes,2,rep,name=changed,proto3" json:"changed,omitempty"`
	InsertedDocs []*Doc  `protobuf:"bytes,3,rep,name=inserted_docs,json=insertedDocs,proto3" json:"inserted_docs,omitempty"`
	ChangedDocs  []*Doc  `protobuf:"bytes,4,rep,name=changed_docs,json=changedDocs,proto3" json:"changed_docs,omitempty"`
}

func (x *ModifyResponse) Reset() {
	*x = ModifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyResponse) ProtoMessage() {}

func (x *ModifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyResponse.ProtoReflect.Descriptor instead.
func (*ModifyResponse) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{18}
}

func (x *ModifyResponse) GetInserted() []*Task {
	if x != nil {
		return x.Inserted
	}
	return nil
}

func (x *ModifyResponse) GetChanged() []*Task {
	if x != nil {
		return x.Changed
	}
	return nil
}

func (x *ModifyResponse) GetInsertedDocs() []*Doc {
	if x != nil {
		return x.InsertedDocs
	}
	return nil
}

func (x *ModifyResponse) GetChangedDocs() []*Doc {
	if x != nil {
		return x.ChangedDocs
	}
	return nil
}

// ModifyDep can be returned with a gRPC NotFound status indicating which
// dependencies failed. This is done via the gRPC error return, not directly
// in the response proto. Either id (for task dependencies) or doc_id (for doc
// dependencies) will be set; msg is used with type=DETAIL for a human-readable
// error message.
type ModifyDep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  ActionType `protobuf:"varint,1,opt,name=type,proto3,enum=api.ActionType" json:"type,omitempty"`
	Id    *TaskID    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Msg   string     `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	DocId *DocID     `protobuf:"bytes,4,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
}

func (x *ModifyDep) Reset() {
	*x = ModifyDep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyDep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyDep) ProtoMessage() {}

func (x *ModifyDep) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyDep.ProtoReflect.Descriptor instead.
func (*ModifyDep) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{19}
}

func (x *ModifyDep) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_CLAIM
}

func (x *ModifyDep) GetId() *TaskID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ModifyDep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ModifyDep) GetDocId() *DocID {
	if x != nil {
		return x.DocId
	}
	return nil
}

// AuthzDep can be returned with a gRPC PermissionDenied status indicating
// which queue/action pairs were not allowed.
type AuthzDep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actions []ActionType `protobuf:"varint,1,rep,packed,name=actions,proto3,enum=api.ActionType" json:"actions,omitempty"`
	// Matching.
	Exact  string `protobuf:"bytes,2,opt,name=exact,proto3" json:"exact,omitempty"`
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Errors. When type is DETAIL.
	Msg string `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AuthzDep) Reset() {
	*x = AuthzDep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthzDep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzDep) ProtoMessage() {}

func (x *AuthzDep) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzDep.ProtoReflect.Descriptor instead.
func (*AuthzDep) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{20}
}

func (x *AuthzDep) GetActions() []ActionType {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AuthzDep) GetExact() string {
	if x != nil {
		return x.Exact
	}
	return ""
}

func (x *AuthzDep) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AuthzDep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// TasksRequest is sent to request a complete listing of tasks for the
// given queue. If claimant_id is empty, all tasks (not just expired
// or owned tasks) are returned.
// Next Tag: 6
type TasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimantId string `protobuf:"bytes,1,opt,name=claimant_id,json=claimantId,proto3" json:"claimant_id,omitempty"`
	Queue      string `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Limit      int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// If IDs are specified here, then any task which matches any of these IDs,
	// and simultaneously fits other specifications, will be returned.
	// If empty, all tasks that fit other specifications will be returned.
	TaskId []string `protobuf:"bytes,4,rep,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// If omit_values is true, then only metadata will be returned, no actual values.
	OmitValues bool `protobuf:"varint,5,opt,name=omit_values,json=omitValues,proto3" json:"omit_values,omitempty"`
}

func (x *TasksRequest) Reset() {
	*x = TasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksRequest) ProtoMessage() {}

func (x *TasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksRequest.ProtoReflect.Descriptor instead.
func (*TasksRequest) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{21}
}

func (x *TasksRequest) GetClaimantId() string {
	if x != nil {
		return x.ClaimantId
	}
	return ""
}

func (x *TasksRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TasksRequest) GetTaskId() []string {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *TasksRequest) GetOmitValues() bool {
	if x != nil {
		return x.OmitValues
	}
	return false
}

// TasksReqponse contains the tasks requested.
type TasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *TasksResponse) Reset() {
	*x = TasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksResponse) ProtoMessage() {}

func (x *TasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksResponse.ProtoReflect.Descriptor instead.
func (*TasksResponse) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{22}
}

func (x *TasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// QueuesRequest is sent to request a listing of all known queues.
type QueuesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchPrefix []string `protobuf:"bytes,1,rep,name=match_prefix,json=matchPrefix,proto3" json:"match_prefix,omitempty"`
	MatchExact  []string `protobuf:"bytes,2,rep,name=match_exact,json=matchExact,proto3" json:"match_exact,omitempty"`
	Limit       int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *QueuesRequest) Reset() {
	*x = QueuesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuesRequest) ProtoMessage() {}

func (x *QueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuesRequest.ProtoReflect.Descriptor instead.
func (*QueuesRequest) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{23}
}

func (x *QueuesRequest) GetMatchPrefix() []string {
	if x != nil {
		return x.MatchPrefix
	}
	return nil
}

func (x *QueuesRequest) GetMatchExact() []string {
	if x != nil {
		return x.MatchExact
	}
	return nil
}

func (x *QueuesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// QueuesResponse contains the requested list of queue statistics.
type QueuesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queues []*QueueStats `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
}

func (x *QueuesResponse) Reset() {
	*x = QueuesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuesResponse) ProtoMessage() {}

func (x *QueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuesResponse.ProtoReflect.Descriptor instead.
func (*QueuesResponse) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{24}
}

func (x *QueuesResponse) GetQueues() []*QueueStats {
	if x != nil {
		return x.Queues
	}
	return nil
}

// TimeRequest asks the server for what it thinks is the current time.
type TimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TimeRequest) Reset() {
	*x = TimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRequest) ProtoMessage() {}

func (x *TimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRequest.ProtoReflect.Descriptor instead.
func (*TimeRequest) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{25}
}

// TimeResponse contains the server's idea of the current time in milliseconds
// since the epoch.
type TimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeMs int64 `protobuf:"varint,1,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
}

func (x *TimeResponse) Reset() {
	*x = TimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entroq_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeResponse) ProtoMessage() {}

func (x *TimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entroq_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeResponse.ProtoReflect.Descriptor instead.
func (*TimeResponse) Descriptor() ([]byte, []int) {
	return file_entroq_proto_rawDescGZIP(), []int{26}
}

func (x *TimeResponse) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

var File_entroq_proto protoreflect.FileDescriptor

var file_entroq_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x48, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x08, 0x54, 0x61,
	0x73, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x13, 0x0a, 0x05,
	0x61, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x61, 0x74, 0x4d,
	0x73, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x5a, 0x0a, 0x0a, 0x54,
	0x61, 0x73, 0x6b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x6f, 0x6c, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x52, 0x05, 0x6f, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x08, 0x6e, 0x65, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07,
	0x6e, 0x65, 0x77, 0x44, 0x61, 0x74, 0x61, 0x22, 0xae, 0x02, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x13, 0x0a, 0x05, 0x61, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x61, 0x74, 0x4d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x6d, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x4d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f,
	0x6d, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x4d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61,
	0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0xc1, 0x01, 0x0a, 0x0a, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e,
	0x75, 0x6d, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6e, 0x75, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x5f,
	0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e,
	0x75, 0x6d, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x75, 0x6d,
	0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x22, 0x81, 0x01, 0x0a,
	0x0c, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x71, 0x75, 0x65, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x6c, 0x6c, 0x5f,
	0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x6c, 0x4d, 0x73,
	0x22, 0x2e, 0x0a, 0x0d, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b,
	0x22, 0x4f, 0x0a, 0x05, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0xe0, 0x01, 0x0a, 0x07, 0x44, 0x6f, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x4b,
	0x65, 0x79, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x6d, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x4d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f,
	0x6d, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x4d, 0x73, 0x22, 0x57, 0x0a, 0x09, 0x44, 0x6f, 0x63, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x21, 0x0a, 0x06, 0x6f, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x52, 0x05, 0x6f,
	0x6c, 0x64, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x44, 0x61, 0x74, 0x61, 0x22, 0xa7, 0x02,
	0x0a, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61, 0x6e, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x61, 0x74, 0x5f,
	0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x61, 0x74, 0x4d, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61,
	0x72, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x6d, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x4d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x5f, 0x6d, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x6f, 0x64,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x4d, 0x73, 0x22, 0xa7, 0x01, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6b, 0x65, 0x79, 0x45, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x6f, 0x6d, 0x69, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x6f, 0x6d, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64,
	0x73, 0x22, 0x77, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6c, 0x61, 0x69, 0x6d, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6c, 0x61, 0x69, 0x6d, 0x61, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x22, 0x32, 0x0a, 0x0b, 0x44, 0x6f,
	0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x6f, 0x63, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x2c,
	0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x22, 0x42, 0x0a, 0x10,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x44, 0x6f, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2e, 0x0a, 0x0b, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x22, 0x31, 0x0a, 0x11, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x44, 0x6f, 0x63, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x52, 0x04, 0x64,
	0x6f, 0x63, 0x73, 0x22, 0x8c, 0x03, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x07, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x73, 0x12,
	0x29, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x73, 0x12, 0x25, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x52,
	0x07, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x2d, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x5f,
	0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x64, 0x6f, 0x63,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x5f, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x64, 0x6f,
	0x63, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x5f,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x5f, 0x64, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x73, 0x22, 0xb8, 0x01, 0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x12, 0x2d, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x6f,
	0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x6f, 0x63, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x44, 0x6f, 0x63, 0x73,
	0x12, 0x2b, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x5f, 0x64, 0x6f, 0x63, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63,
	0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x44, 0x6f, 0x63, 0x73, 0x22, 0x82, 0x01,
	0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x44, 0x65, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x21, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x49, 0x44, 0x52, 0x05, 0x64, 0x6f, 0x63,
	0x49, 0x64, 0x22, 0x75, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x7a, 0x44, 0x65, 0x70, 0x12, 0x29,
	0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x61,
	0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x61, 0x63, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x95, 0x01, 0x0a, 0x0c, 0x54, 0x61,
	0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c,
	0x61, 0x69, 0x6d, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x6d, 0x69, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6f, 0x6d, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x22, 0x30, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74, 0x61,
	0x73, 0x6b, 0x73, 0x22, 0x69, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x70, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x65, 0x78, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x45, 0x78, 0x61, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x39,
	0x0a, 0x0e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x27, 0x0a, 0x06, 0x71, 0x75, 0x65, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x06, 0x71, 0x75, 0x65, 0x75, 0x65, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x0c, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x4d,
	0x73, 0x2a, 0x5d, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x09, 0x0a, 0x05, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x50, 0x45, 0x4e, 0x44, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e,
	0x53, 0x45, 0x52, 0x54, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41, 0x44, 0x10, 0x06,
	0x32, 0x90, 0x06, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x72, 0x6f, 0x51, 0x12, 0x4b, 0x0a, 0x08, 0x54,
	0x72, 0x79, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x2f,
	0x63, 0x6c, 0x61, 0x69, 0x6d, 0x3a, 0x01, 0x2a, 0x12, 0x4d, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17,
	0x22, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x2f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x2f,
	0x77, 0x61, 0x69, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x4c, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x13, 0x22, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x2f, 0x6d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x3a, 0x01, 0x2a, 0x12, 0x45, 0x0a, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x11,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x49, 0x0a, 0x06,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30,
	0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x73, 0x12, 0x53, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x2f,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x41, 0x0a, 0x04,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0e, 0x12, 0x0c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x54, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x11,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x30, 0x01, 0x12, 0x41, 0x0a, 0x04, 0x44, 0x6f, 0x63, 0x73, 0x12, 0x10, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x30, 0x2f, 0x64, 0x6f, 0x63, 0x73, 0x12, 0x59, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x44, 0x6f, 0x63, 0x73, 0x12, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x44, 0x6f, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x44, 0x6f, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x12, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x30, 0x2f, 0x64, 0x6f, 0x63, 0x73, 0x2f, 0x63, 0x6c, 0x61, 0x69, 0x6d,
	0x3a, 0x01, 0x2a, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x68, 0x69, 0x62, 0x6c, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x71,
	0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entroq_proto_rawDescOnce sync.Once
	file_entroq_proto_rawDescData = file_entroq_proto_rawDesc
)

func file_entroq_proto_rawDescGZIP() []byte {
	file_entroq_proto_rawDescOnce.Do(func() {
		file_entroq_proto_rawDescData = protoimpl.X.CompressGZIP(file_entroq_proto_rawDescData)
	})
	return file_entroq_proto_rawDescData
}

var file_entroq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entroq_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_entroq_proto_goTypes = []interface{}{
	(ActionType)(0),           // 0: api.ActionType
	(*TaskID)(nil),            // 1: api.TaskID
	(*TaskData)(nil),          // 2: api.TaskData
	(*TaskChange)(nil),        // 3: api.TaskChange
	(*Task)(nil),              // 4: api.Task
	(*QueueStats)(nil),        // 5: api.QueueStats
	(*ClaimRequest)(nil),      // 6: api.ClaimRequest
	(*ClaimResponse)(nil),     // 7: api.ClaimResponse
	(*DocID)(nil),             // 8: api.DocID
	(*DocData)(nil),           // 9: api.DocData
	(*DocChange)(nil),         // 10: api.DocChange
	(*Doc)(nil),               // 11: api.Doc
	(*DocQuery)(nil),          // 12: api.DocQuery
	(*DocClaim)(nil),          // 13: api.DocClaim
	(*DocsRequest)(nil),       // 14: api.DocsRequest
	(*DocsResponse)(nil),      // 15: api.DocsResponse
	(*ClaimDocsRequest)(nil),  // 16: api.ClaimDocsRequest
	(*ClaimDocsResponse)(nil), // 17: api.ClaimDocsResponse
	(*ModifyRequest)(nil),     // 18: api.ModifyRequest
	(*ModifyResponse)(nil),    // 19: api.ModifyResponse
	(*ModifyDep)(nil),         // 20: api.ModifyDep
	(*AuthzDep)(nil),          // 21: api.AuthzDep
	(*TasksRequest)(nil),      // 22: api.TasksRequest
	(*TasksResponse)(nil),     // 23: api.TasksResponse
	(*QueuesRequest)(nil),     // 24: api.QueuesRequest
	(*QueuesResponse)(nil),    // 25: api.QueuesResponse
	(*TimeRequest)(nil),       // 26: api.TimeRequest
	(*TimeResponse)(nil),      // 27: api.TimeResponse
	(*structpb.Value)(nil),    // 28: google.protobuf.Value
}
var file_entroq_proto_depIdxs = []int32{
	28, // 0: api.TaskData.value:type_name -> google.protobuf.Value
	1,  // 1: api.TaskChange.old_id:type_name -> api.TaskID
	2,  // 2: api.TaskChange.new_data:type_name -> api.TaskData
	28, // 3: api.Task.value:type_name -> google.protobuf.Value
	4,  // 4: api.ClaimResponse.task:type_name -> api.Task
	28, // 5: api.DocData.content:type_name -> google.protobuf.Value
	8,  // 6: api.DocChange.old_id:type_name -> api.DocID
	9,  // 7: api.DocChange.new_data:type_name -> api.DocData
	28, // 8: api.Doc.content:type_name -> google.protobuf.Value
	12, // 9: api.DocsRequest.query:type_name -> api.DocQuery
	11, // 10: api.DocsResponse.docs:type_name -> api.Doc
	13, // 11: api.ClaimDocsRequest.claim_query:type_name -> api.DocClaim
	11, // 12: api.ClaimDocsResponse.docs:type_name -> api.Doc
	2,  // 13: api.ModifyRequest.inserts:type_name -> api.TaskData
	3,  // 14: api.ModifyRequest.changes:type_name -> api.TaskChange
	1,  // 15: api.ModifyRequest.deletes:type_name -> api.TaskID
	1,  // 16: api.ModifyRequest.depends:type_name -> api.TaskID
	9,  // 17: api.ModifyRequest.doc_inserts:type_name -> api.DocData
	10, // 18: api.ModifyRequest.doc_changes:type_name -> api.DocChange
	8,  // 19: api.ModifyRequest.doc_deletes:type_name -> api.DocID
	8,  // 20: api.ModifyRequest.doc_depends:type_name -> api.DocID
	4,  // 21: api.ModifyResponse.inserted:type_name -> api.Task
	4,  // 22: api.ModifyResponse.changed:type_name -> api.Task
	11, // 23: api.ModifyResponse.inserted_docs:type_name -> api.Doc
	11, // 24: api.ModifyResponse.changed_docs:type_name -> api.Doc
	0,  // 25: api.ModifyDep.type:type_name -> api.ActionType
	1,  // 26: api.ModifyDep.id:type_name -> api.TaskID
	8,  // 27: api.ModifyDep.doc_id:type_name -> api.DocID
	0,  // 28: api.AuthzDep.actions:type_name -> api.ActionType
	4,  // 29: api.TasksResponse.tasks:type_name -> api.Task
	5,  // 30: api.QueuesResponse.queues:type_name -> api.QueueStats
	6,  // 31: api.EntroQ.TryClaim:input_type -> api.ClaimRequest
	6,  // 32: api.EntroQ.Claim:input_type -> api.ClaimRequest
	18, // 33: api.EntroQ.Modify:input_type -> api.ModifyRequest
	22, // 34: api.EntroQ.Tasks:input_type -> api.TasksRequest
	24, // 35: api.EntroQ.Queues:input_type -> api.QueuesRequest
	24, // 36: api.EntroQ.QueueStats:input_type -> api.QueuesRequest
	26, // 37: api.EntroQ.Time:input_type -> api.TimeRequest
	22, // 38: api.EntroQ.StreamTasks:input_type -> api.TasksRequest
	14, // 39: api.EntroQ.Docs:input_type -> api.DocsRequest
	16, // 40: api.EntroQ.ClaimDocs:input_type -> api.ClaimDocsRequest
	7,  // 41: api.EntroQ.TryClaim:output_type -> api.ClaimResponse
	7,  // 42: api.EntroQ.Claim:output_type -> api.ClaimResponse
	19, // 43: api.EntroQ.Modify:output_type -> api.ModifyResponse
	23, // 44: api.EntroQ.Tasks:output_type -> api.TasksResponse
	25, // 45: api.EntroQ.Queues:output_type -> api.QueuesResponse
	25, // 46: api.EntroQ.QueueStats:output_type -> api.QueuesResponse
	27, // 47: api.EntroQ.Time:output_type -> api.TimeResponse
	23, // 48: api.EntroQ.StreamTasks:output_type -> api.TasksResponse
	15, // 49: api.EntroQ.Docs:output_type -> api.DocsResponse
	17, // 50: api.EntroQ.ClaimDocs:output_type -> api.ClaimDocsResponse
	41, // [41:51] is the sub-list for method output_type
	31, // [31:41] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_entroq_proto_init() }
func file_entroq_proto_init() {
	if File_entroq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entroq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocClaim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimDocsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimDocsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyDep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthzDep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueuesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueuesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entroq_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entroq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entroq_proto_goTypes,
		DependencyIndexes: file_entroq_proto_depIdxs,
		EnumInfos:         file_entroq_proto_enumTypes,
		MessageInfos:      file_entroq_proto_msgTypes,
	}.Build()
	File_entroq_proto = out.File
	file_entroq_proto_rawDesc = nil
	file_entroq_proto_goTypes = nil
	file_entroq_proto_depIdxs = nil
}
